### ISSUE TITLE
Registration and Log In [5]

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#400]
Test the log in flow and see if there are any immediate improvements we should be suggesting.  Word is coming in that some users are not making it to OpenShift.io - they end up in OpenShift somehow.  

Jake Lucky, Dan, and Alexey are point developers for questions.

**Comment by catrobson** [comment]
You should be able to test this flow using production.

**Comment by sdash-redhat** [comment]
I landed in the blank white page after login in prod preview. 

<img width="1440" alt="screen shot 2017-04-25 at 5 51 48 pm" src="https://cloud.githubusercontent.com/assets/27761023/25385174/cf374372-29e0-11e7-9b4d-b832869649a1.png">

**Comment by catrobson** [comment]
We are now capturing the current flows for Log and and Registration here:
https://redhat.invisionapp.com/d/main#/projects/prototypes/11000193
