### ISSUE TITLE
consistent typeahead boxes for lists

### ISSUE THREAD

**Issue by maxandersen** [fabric8-ui/fabric8-ux#407]
This is a follow up discussion on MM: https://chat.openshift.io/rh-devtools/pl/o4da3gkrtib7uxkj4ypowcrady

Main gist is that we seem to have multiple different combobox'es used for anything that has a list of possible options and in conversation @mindreeper2420 mentioned we just needed two - one with typeahead and one without.

For me that means that in some cases we'll have a list selection where I have to use the arrow keys or mouse instead of just typing part of the name as is available in other search/combo boxes.

My suggestion was to provide the same kind of type-ahead-boxes everywhere instead of switching between the two based on what absolute number of items is expected to be in the list.

**Comment by catrobson** [comment]
Being work on in this issue:  https://github.com/fabric8-ui/fabric8-ux/issues/516
