### ISSUE TITLE
WIREFRAMES/GUIDELINES: Error checking for names

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#418]
Draft specs (with supporting wireframes, if needed) to define what the Name text field for iterations, areas, and others will support.

- Max length
- Required
- Special characters allowed/disallowed
- Uniqueness

**Comment by muruGanesan** [comment]
I will work with Dev team and create a draft and socialize with UX team

**Comment by sdash-redhat** [comment]
Starting on this. 
Assuming this is for name filed and any other similar fields like description, short desc etc.

**Comment by sdash-redhat** [comment]
As per discussion with Gorkem & team, the Openshift will have an upstream Che ide which will be at beginning closer to the hosted Che Ide at Codenvy. So accessed the code-envy and grabed the HTML Doms with CSS/JS that represent each views that will help in inspecting the related CSS to hack into the theme to get the new theme. 

Get the saved HTMLs here ..just extract from zip and click to run - 

Also attached some sceen-shots for quick view here: 
https://docs.google.com/presentation/d/1vb2BjyVOYHn4tBHSHg12lBjmmwDC4oiPCX_QfV74LvY/edit#slide=id.p4 

Hope this helps!
@catrobson @sunilmalagi @muruGanesan @mindreeper2420 @bdellasc

**Comment by catrobson** [comment]
I think the major ones of concern are:

- Work item name
- Iteration name
- Space name

Fields like description probably have different requirements.  We can start capturing all in one document though if that makes sense to have as a master reference.

**Comment by sdash-redhat** [comment]
Based on the explorations on the best practices used across industry , have created the list and provided two angles -- 
1. While input what can be the character limit restrictions. 
2. While displaying how much minimum characters we should display before allowing the truncating the string with ellipsis (...)

https://redhat.invisionapp.com/share/D4BW80NFC

Refer to the appendix of the guideline for references and getting an understanding behind the numbers finalised. 

@muruGanesan @catrobson @Essjaysee @mindreeper2420 @bdellasc

**Comment by sdash-redhat** [comment]
(For ref https://docs.google.com/a/redhat.com/presentation/d/1KUuD6kZbFEXIRHhoNc-X95k7bnvr5TFgbwhVMAr1RAk/edit?usp=sharing)
