### ISSUE TITLE
WIREFRAME/VISUAL: Hierarchical presentation of areas

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#420]
Create designs that show how to present the areas as paths and in a hierarchical view.  

Also, related concerns/questions from the UX workshop:
- Consider adding a description field
- Explore showing collaborators (or not) on the areas page

(We agreed that the space name wouldn't appear on the page, but the rest of the presentation is up for grabs.)

**Comment by sunilmalagi** [comment]
Is someone working on the wireframe?  How do we go about it?
