### ISSUE TITLE
WIREFRAMES: Iterating on iterations [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#423]
Odds and ends around iterations and the left panel.

From the UX workshop:
- Define interactions for dragging and dropping a WI onto an iteration (this probably already exists)
- (Separate story: #440) Define logic around starting an iteration that has children: do the children start as well?
- Remove space from the iteration path
- Check the indentation in visuals for current vs. future iterations
- Make sure dev has the latest designs/visuals for collapsible panel. [Visual story here](https://github.com/fabric8io/fabric8-ux/issues/319)

**Comment by sunilmalagi** [comment]
Is someone working on the wireframe?  How do we go about it?

**Comment by Essjaysee** [comment]
Breaking the second bullet into a separate story:  https://github.com/fabric8io/fabric8-ux/issues/440

**Comment by Essjaysee** [comment]
Last bullet is related to https://github.com/fabric8io/fabric8-ux/issues/319

**Comment by Essjaysee** [comment]
@mindreeper2420 Can you help me with the fourth bullet (indentation)?  It seems like it might be as simple as adjusting the spacing to match the specs at https://redhat.invisionapp.com/share/FR9R8G6B9#/screens/211643012/comments

**Comment by mindreeper2420** [comment]
@essjaysee sure thing. I can take a look while in the office so that you and Brian can verify.

**Comment by mindreeper2420** [comment]
In order to properly implement the collapsible panel, the layout will need to be returned to the grid style that the designs were built off of. I spoke with Michael K. on a timeframe for removing the flex overlay, but not timetable was given.
