### ISSUE TITLE
WIREFRAMES:  Notifications

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#432]
Draft wireframes and interaction specs to support email notifications.

- For now, it's on/off, all/none...so where do you enable/disable them?
- Copy for the notifications themselves

From Platform MVP Document:
- email notifications service - component based definition of what to send...
-- Investigate
-- management of notifications - platform/components…
- Discover/register notifications available and management within platform
-- Across component notifications - events/mentions or actions
-- In platform toast notifications, action/event notifications
- Discover/register notifications available and management within platform
- Planner - first customer - 
-- Get notified on updates to work items creator has added - creator notification - always
-- Get notified on all updates of work items you have participated on (creator, assignee, commenter, etc.)
-- Be able to mute notifications (all or nothing…) - by type of notification
- Support Mentions

**Comment by zhutaoredhat** [comment]
Hi Sj,
Here is a new mockup about this issue, I think It was created by adam. https://redhat.invisionapp.com/share/C5CWDPFP2#/screens/247009684  The mockup covers most features in this issue looks great. Do you think it is make sense?

I have some other questions about this issue:
1.I am not clear about the meaning of "Copy for the notifications themselves". why we will do this thing?
2.About management notification, except “read”“delete”, what else functions do we need?

I had try to create a notification-drawer today, please have a review.
![Uploading notification-drawer.png…]()
![Uploading notification-drawer-callouts.png…]()

Thank you~

**Comment by Essjaysee** [comment]
Hi @zhutaoredhat, thanks for posting the design!  I just have a couple of questions:

- Does this list include only the unread/new events?  How would I find read/old events?
- Did you consider showing the avatar photo for each instance of a user's name, or would that be too cluttered?

Regarding your questions:
1.  Sorry that wasn't clear. I mean that we need to write the text of the notifications (rather than just provide the design for them) or find out who the technical writer is who is working on the project with us and ask him/her to help.
2.  Read and delete functions for the notifications are sufficient for now.

I hope that helps clarify.  Please let me know if you have any other questions!

**Comment by zhutaoredhat** [comment]
@Essjaysee Hi, thanks for your quick feedback. That is much more clear to me.
The demo updated yesterday doesn't include the read events, sorry for the confusing. I had updated the new demo below. 
![update](https://user-images.githubusercontent.com/13375283/29067410-0ffa9874-7c65-11e7-8bae-29a61988dd86.png)
**Updates:**
1. Update different read status.
2. Add comment update template.
3. Update the time format to "1 min ago" "2 hours ago" "3 days ago" ...I think it will be much more friendly for the guys work in different time zone and the clearer time to get when the event happened. Do you agree with this opinion?

I had try to create a demo show all the user's name with a avatar photo (the list on the right) ever, it looks a little cluttered.

Is there something else need to improve?

**Comment by Essjaysee** [comment]
@zhutaoredhat Thanks for the updates!  It looks good to me, nice job.  What do you think, @catrobson?

**Comment by catrobson** [comment]
@zhutaoredhat I think that we should be grouping by space rather than by my notifications vs. others notifications.  Maybe at the top we would have general system notifications.  So then you would have:

SYSTEM
SPACENAME1
SPACENAME2

It would show spaces that I own or am collaborating on that currently have notifications.  Does that sound good?

**Comment by zhutaoredhat** [comment]
@catrobson Waoh, that's a great idea. I had updated the mockup:
![1](https://user-images.githubusercontent.com/13375283/29116686-2687c022-7ceb-11e7-85ba-29a3065d3668.png)
But when I was making the mockup, I met a new question. Will the user have a lot of spaces?
So I designed the mockup2 with the lables to separate events form different spaces.
 Could you give me some examples about system examples to me please? I would like design some system notification template. Such as "System Update - The system will be update at ..." 
![2](https://user-images.githubusercontent.com/13375283/29117277-280d7d36-7ced-11e7-93d3-d5310bf54a36.png)
The notification setting page should be updated either. Added the switch button to each space.
![3](https://user-images.githubusercontent.com/13375283/29117395-8efaeb96-7ced-11e7-8d42-152d277f8a2f.png)
![4](https://user-images.githubusercontent.com/13375283/29117403-926d01d8-7ced-11e7-8e8b-4d38ae1e988a.png)

**Comment by catrobson** [comment]
@zhutaoredhat - Thanks for the updates!  I think we would not show a space grouping if it has 0 notifications to keep down the noise in the panel.  Would that make sense to you?

I think, especially initially, the number of spaces that a user is collaborating on and actively getting notifications on will be somewhat limited - just like Github there are probably only 6 or so projects that you can really *actively* watch before it gets too much to handle.    Therefore I'd like to start with it breaking out the spaces by name rather than grouping all spaces into one bucket and get some user feedback on it as we go along to see if we need to alter it from there.

We also like your concepts for managing notifications at each space in the profile.  I think something like this would work well to start, and then we just might need to reassess when we get to the point that people are collaborating on a whole lot of spaces.

**Comment by zhutaoredhat** [comment]
Hi @catrobson I love the idea of Space group, but we still may meet some extreme case:
![n3](https://user-images.githubusercontent.com/13375283/29206398-66499e4a-7eb4-11e7-883d-bd150664e0a7.png)
The operation zone looks a little small.
So I try some other ways to show notifications
1.Use wide Notification Drawer in default.
![r44](https://user-images.githubusercontent.com/13375283/29211276-b7e962b0-7eca-11e7-8b10-ef869ceb0b62.png)
2.Give up Notification Drawer 
![r15](https://user-images.githubusercontent.com/13375283/29211424-9a4ff254-7ecb-11e7-90ea-67a63d68b2d2.png)
The idea is not mature yet...

**Comment by catrobson** [comment]
I agree we have a limit problem with the current PatternFly interaction for the notification drawer. We will definitely want a page for notifications, sort of like github does (https://github.com/notifications) for fuller viewing and management of the notifications.  I'd also like the drawer as a quick view mechanism without going to the full page though.  Maybe we do go with the system, space breakdown and only show the last x number, and then link off to the full page to view all where they can see them categorized by space?  I do like how Github has in page navigational links that can quickly filter the view to just a space.  Open to some other ideas here as well!

**Comment by zhutaoredhat** [comment]
@catrobson Great idea!~  In my daily life,  most notifications will be checked through email notifications. I had never opened github notification before. : (
I updated a new mockup:
![h7](https://user-images.githubusercontent.com/13375283/29267591-e44afe38-811b-11e7-81d5-5761e0d01a10.png)
1. The link to the full page
2. Quick filters
: )

**Comment by catrobson** [comment]
@zhutaoredhat Can we use the header rollup information that you see in Colleen's OpenShift design here:  http://openshift.github.io/openshift-origin-design/web-console/4-patterns/notifications

I think if we show this per space header, the user could then click through to the notifications page, filtered to the space they selected.

Could you take this story forward by doing a full set of wireframes (low fidelity please) showing all the design and interaction points for this concept?

**Comment by zhutaoredhat** [comment]
@catrobson Sure, I will continue this issue. Thanks for your feedback~

**Comment by zhutaoredhat** [comment]
Hi @catrobson I have update the full set of wireframes. Please have a review https://redhat.invisionapp.com/share/QVDA5TLE4

**Comment by catrobson** [comment]
@zhutaoredhat when you get a chance, could you update these wireframes to show the notifications page w/ user's notifications as accessible from the left hand dropdown under a new menu item "My Notifications" underneath "account home"?
![image](https://user-images.githubusercontent.com/3739227/30786876-023fb79a-a14b-11e7-977b-ff350ee6fe71.png)

I'm thinking it won't make sense for the user to go to their settings to view their notifications, that should live in a separate place in the IA.

We'll then have Settings in the user settings area, but viewing notifications would be done under this new navigational item if the user goes from the notification drawer to full screen viewing of their notifications.  If you can reflect the settings area wireframes and full page notification page to reflect this it would be appreciated!

**Comment by zhutaoredhat** [comment]
@catrobson I have updated the all wireframes. https://redhat.invisionapp.com/d/main/#/projects/prototypes/11914584
There will be two entrances to go to the notification page.
![notification-entrances 2x](https://user-images.githubusercontent.com/13375283/30901833-e2d194fc-a39b-11e7-8300-69ff5cddc36e.png)
Dose that make sense?

**Comment by catrobson** [comment]
Makes sense for now, we need to take a look at improving the nav anyway.  Can you remove the notifications tab from the settings page wireframe?  Otherwise looks good!

**Comment by zhutaoredhat** [comment]
@catrobson Oh,sorry. I had missed this comment.

**Comment by zhutaoredhat** [comment]
![notification-settings22 2x](https://user-images.githubusercontent.com/13375283/31929509-f36223c0-b8ce-11e7-904e-5cc8779ad61e.png)
Hi @catrobson , If I remove the notifications tab, it will be looks like this. I am not clear where is the "Entrance" to notification settings and the left navigation looks useless. should I remove the Vertical navigation？

**Comment by junezhang** [comment]
@zhutaoredhat, the notification tab should be the space tab, not on the left nav part, currently we were not going to get this granular for notification at this point. It would just be all on or off for a space's notification.
Look like the wireframe from Brain as below:
<img width="1319" alt="screen shot 2017-10-24 at 3 41 26 pm" src="https://user-images.githubusercontent.com/701009/31930296-e3625680-b864-11e7-838d-da0e27afe677.png">

**Comment by zhutaoredhat** [comment]
@junezhang Got it, thanks

**Comment by zhutaoredhat** [comment]
@catrobson Updated, please ignore the message above.

**Comment by catrobson** [comment]
@Essjaysee and Cat to do a review to close out IXD work this week.

**Comment by catrobson** [comment]
Closing this story, updates have been made to reflect latest design thinking in this area.

**Comment by zhutaoredhat** [comment]
@catrobson Got it, thanks~
