### ISSUE TITLE
WORKFLOW:  Designate log-in points throughout the system

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#442]
Most of the system should be accessible to users in a read-only state.  Assemble a doc, rules, or other documentation that designates when users should be asked to log in before proceeding.

**Comment by joshuawilson** [comment]
There are 2 paths in this to consider. 
 1.  Comments can be entered by anyone but they must be logged in, in order to add them
 2.  Editing an Area requires login and permissions

**Comment by catrobson** [comment]
Added pages that require log-in here:  https://docs.google.com/spreadsheets/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit#gid=208615194
