### ISSUE TITLE
WIREFRAME: Space Dashboard

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#443]
Ideal design of space dashboard to give the user an overview of everything they might care about that is happening in the system.

**Comment by catrobson** [comment]
Consider work done by the Beijing team here:  https://github.com/fabric8-ui/fabric8-ux/issues/693

**Comment by lwrigh** [comment]
@catrobson Here is a first pass at the space dashboard: 

Invision link: https://redhat.invisionapp.com/share/F6FETDZBA2D

**Comment by lwrigh** [comment]
@catrobson I added a few more concepts to the Invision doc: 

Invision link: https://redhat.invisionapp.com/share/F6FETDZBA2D

**Comment by lwrigh** [comment]
I included a couple variations of the dashboard concepts that include error states (#791)

**Comment by lwrigh** [comment]
@catrobson Some edits that I made to the space dashboard include a create new issue widget, the addition of a small pipeline visualization to the my pipelines widget, and the addition of more visual elements to the dashboard. 

https://redhat.invisionapp.com/share/DQFLCG4G9YK

**Comment by lwrigh** [comment]
![image](https://user-images.githubusercontent.com/20227374/35743228-f1553f50-080a-11e8-823e-c3718eb58c2e.png)
 Combined widget

**Comment by lwrigh** [comment]
@Veethika @parvathyvr Here is the space dashboard issue that is connected to the analytics widget

**Comment by Veethika** [comment]
Thanks Laura.
Will go through it and connect with you on Mattermost if there's any
confusion.



VEETHIKA MISHRA

INTERACTION DESIGNER

Red Hat

<https://www.redhat.com/>

M: +91-7561063455
<https://red.ht/sig>

**Comment by lwrigh** [comment]
@catrobson Adding more applications to the active applications widget to see how it would scale. I also experimented with a list view in that widget to see how it would look and act. https://redhat.invisionapp.com/share/DQFLCG4G9YK

**Comment by lwrigh** [comment]
Here's the latest iteration of the space dashboard based off of feedback from @muruGanesan and design review. The Invision document features some of the error states featured in [791](https://github.com/fabric8-ui/fabric8-ux/issues/791) https://redhat.invisionapp.com/share/DQFLCG4G9YK

**Comment by lwrigh** [comment]
Wireframes w/ notes: https://redhat.invisionapp.com/share/DQFLCG4G9YK
