### ISSUE TITLE
WIREFRAME:  Space wizard rethink

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#444]
Reconsider the space wizard from user driven requirements and an understanding of current capabilities.

Some input:
> more of a UX question than anything else really. Right now we've 1 wizard which just uses the RHOAR wizards (vertx, spring boot, WF swarm) but we've loads more quickstarts we could let users use (node, php, C++, go, swift, ruby, python et al - together with camel/fuse quickstarts too).
> 
> So we maybe need a way to pick which 'set' of quickstarts to choose from first? Then we can let users pick from the available ones?
> 
> Or do we need a more sophisticated UI to let folks pick what quickstarts to be shown? e.g. we may want to disable upstream quickstarts for some users?
> right now we have 2 separate wizards for RHOAR and upstream quickstarts; which isn't an awesome UX - wonder if we need a better combined wizard that groks all possible quickstarts with a nice way to filter/choose?

**Comment by jstrachan** [comment]
I guess a quick fix would be to move the 'combo box' widget to the first page of wizard and present a more browse/search page first that let folks filter by tech stack (spring boot, vertx, WF Swarm, nodejs, whatever); then the rest of the wizard would then appear as next pages?

**Comment by catrobson** [comment]
Posted new wireframes into InVision:  https://redhat.invisionapp.com/share/DUD3OHBMP
