### ISSUE TITLE
[VISUALS] Design a "_notauthorized" page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#462]
As discussed in https://github.com/fabric8io/fabric8-ui/issues/1393, we'll need a page that helps users understand they are not authorized to view a particular page and help them recover from this (navigate to other pages that might make sense - how they can request access maybe?)

**Comment by bdellasc** [comment]
Posted a layout to InVision. It's based on the 404 error page layout.

[https://redhat.invisionapp.com/share/S6CPDL95E#/245017779_A-0100](https://redhat.invisionapp.com/share/S6CPDL95E#/245017779_A-0100)

**Comment by bdellasc** [comment]
Updated the InVision mockup. Enclosed is the sample HTML page with the SVG animation in it.

[fingerprint_scanner_html.zip](https://github.com/fabric8-ui/fabric8-ux/files/1184387/fingerprint_scanner_html.zip)
