### ISSUE TITLE
Segment the InVision Links page into components

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#490]
We currently have one long list of all the invision links.  To make it easier to parse, let's segment the design links into:  Planner, Platform, Bayesian.  If we want to future proof we could also add Hypothesis.

**Comment by mindreeper2420** [comment]
Reviewed updates with Cat - updating some of the tables to change design associations. Create a "fabric8 Patterns" page that will contain the patterns that are shared across the product (menus, icons, save/edit models, etc.).
