### ISSUE TITLE
DESIGN: Updating the user status 

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#491]
- Updating and reworking the user status that features all of the version numbers 
- Review feature with Cat 
- Come up with alternative concepts 
- Visuals will be needed 
- Consider an idle status 
- Add analytics to the status bar as well

**Comment by lwrigh** [comment]
About modal with version numbers on it. 

https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtU2ZFMzhOVEVKZnM/view?usp=sharing

Any feedback or comments on it are welcome! @bdellasc @mindreeper2420 @catrobson

**Comment by lwrigh** [comment]
Idle status and icon

https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtZXZjSHNBdE5pU0U/view?usp=sharing

Any feedback or comments on it are welcome! @bdellasc @mindreeper2420 @catrobson

**Comment by lwrigh** [comment]
Status bar with different layout options. Also included is an exploration of what would happen if a user clicked on the red x icon and some sort of error message popped up to let them know what the error might be. 

https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtS05mVl9yMWhaUlU/view?usp=sharing

Any feedback or comments on it are welcome! @bdellasc @mindreeper2420 @catrobson

**Comment by Essjaysee** [comment]
@lwrigh Thanks for posting these!

On the about modal, is there a particular reason to show all the detail in the time stamp?  Sometimes there is, so I wanted to ask before just suggesting that maybe we change that to a more human-readable format.

On the status that has children, what would show on the parent if one child was green and the other red?  Is that even a case it could get into?  Same question, I guess, for the rollup icon on the navigation bar -- does it show the most severe (worst?) status icon?

**Comment by lwrigh** [comment]
@Essjaysee Thank you for the feedback SJ! The timestamp is currently like that so I pulled from what is already on the current about modal but I totally agree that a more human format would be easier to read. I can make a version that features a more human time stamp for comparison. 

That is an excellent question. I am not exactly sure what would happen in that situation.

Do you know what that sort of use case would mean on the technical side?  

"On the status that has children, what would show on the parent if one child was green and the other red? Is that even a case it could get into? Same question, I guess, for the rollup icon on the navigation bar -- does it show the most severe (worst?) status icon?"

@dgutride @dlabrecq @catrobson

**Comment by lwrigh** [comment]
Updates: 

Here are the links to edited versions of the status bar and about modal based off of feedback: 

About modal: 
https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtMENOZzVTQ3NWUXM/view?usp=sharing

A more human timestamp (based off of the timestamp from Planner) was added to the about modal.

Status bar: 
https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5Mtelg2OUd3cFhmZVk/view?usp=sharing

Different layouts (nested vs. not nested) were explored and subtle, horizontal lines were added to demarcate the platforms into categories.

Status bar tooltips & version numbers: 
https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5Mtd3NLMHRCcDFlbkk/view?usp=sharing

Tooltips were added to each status in order to let the user hover over the item in order to see the current running version number. Tooltips, info buttons, and accordions were experimented with.    

Any feedback or comments are much appreciated! Let me know if there is any other information that should be easy to surface from the status bar.

**Comment by catrobson** [comment]
I think the rules are not helping in the status pop-up, its too much clutter.   I feel like indenting without the bars worked best to organize the information.

Sorry if I wasn't clear in my ask for the version numbers.  I actually meant that we need a way to capture all the version numbers for all components within the about box, not within the status bar.  We can review tomorrow if you'd like Laura!

**Comment by lwrigh** [comment]
That would be helpful, I can send you an event invite.

**Comment by lwrigh** [comment]
Based off of feedback from our meeting this morning, I made edits to the about modal and the status bar. I also played around with the idea of having an info tip next to the component if there was a caution or an error associated with it. It does feature a pop up within a pop up however so let me know what you think about that.  

About modal: https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtRDQ5aEpOWEotYU0/view?usp=sharing

Status bar: 
https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtS0xDUkV3Y1FkczQ/view?usp=sharing

Status bar with error message: 
https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5MtRGJ5YWNSN2VTVEE/view?usp=sharing

**Comment by lwrigh** [comment]
![screen shot 2017-06-30 at 9 42 27 am](https://user-images.githubusercontent.com/20227374/27738130-7f864c1c-5d78-11e7-9aea-588b7947fec9.png)

Here is the status bar with an error message without the info icon
