### ISSUE TITLE
Sync PatternFly-ng and ng-widgets to PatternFly Styles

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#493]

**Comment by dlabrecq** [comment]
FYI, patternfly-ng only references Patternfly variables. We don't compile Patternfly CSS, but use whatever version that fabric8 includes in the page.

**Comment by mindreeper2420** [comment]
Per the note from Dan, I'm going to close this issue and create another for syncing OSio style to that of PatternFly. That will remove any additional styles that are unnecessary and provide clearer direction of staying in sync.
