### ISSUE TITLE
Create MVP definition for Hypothesis Engine

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#515]
Given work we have done in the past week, work towards a definition of MVP for the hypothesis engine.  This should define what screens we will be focusing on for the MVP.

**Comment by lwrigh** [comment]
[Hypothesis_Wireframes w: user flow v1.pdf](https://github.com/fabric8-ui/fabric8-ux/files/1135649/Hypothesis_Wireframes.w.user.flow.v1.pdf)
[Hypothesis Workflows v1.zip](https://github.com/fabric8-ui/fabric8-ux/files/1135650/Hypothesis.Workflows.v1.zip)
![img_20170707_144428490](https://user-images.githubusercontent.com/20227374/28020721-58e453be-6553-11e7-90d8-30efff8081bd.jpg)
