### ISSUE TITLE
Design standard multi-select type-ahead dropdown

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#516]
Design a standard multi-select type-ahead dropdown that we can custom build and use as a shared component across OSIO.

Consider PatternFly standards, but we want to create an advanced control that can handle OSIO situations.  Current implementations in OSIO that aren't quite perfect and all seem to be a bit different:

![image](https://user-images.githubusercontent.com/3739227/28853026-89d80a7e-76fb-11e7-90a5-c223820091d1.png)

![image](https://user-images.githubusercontent.com/3739227/28853038-990aab00-76fb-11e7-937f-1cf1eb3d3698.png)

![image](https://user-images.githubusercontent.com/3739227/28853047-b40868de-76fb-11e7-805a-da21e7641c70.png)

![image](https://user-images.githubusercontent.com/3739227/28853054-c6ad9f2c-76fb-11e7-99e9-26c8446e9f8e.png)

**Comment by yih-wang** [comment]
@catrobson I went over the scenarios mentioned above in OSIO and found they all don't support multi-select for now. Lacking of reference, I'm wondering what extra functions we want to add beyond the PatternFly standards. From my perspective, PatternFly multi-select is enough for these scenarios. The demo of PatternFly multi-select can be found here: http://www.patternfly.org/pattern-library/widgets/#bootstrap-select

**Comment by catrobson** [comment]
@yih-wang - Angular-ng isn't able to use the regular PatternFly dropdown, so we want to create one that does everything we need in all situations.  I think this means that we want to take the following options of PatternFly and smoosh them into one widget:

Bootstrap Combo-box:  Type search capability to narrow the options
![image](https://user-images.githubusercontent.com/3739227/29052803-5b51e51c-7bba-11e7-931b-907351ece598.png)

Bootstrap Muliselect:  Select one or many options in the dropdown, and then show multiple selections when the dropdown is closed
![image](https://user-images.githubusercontent.com/3739227/29052793-4deb5660-7bba-11e7-93b2-6f8ea3fde192.png)

Hierarchical Support:  As you can see many of the dropdowns today are showing parent/child/grandchild relationships with / between them.  This is not ideal.  Ideally the dropdown should support indenting to show parent/child relationships.

Hope this helps clarify the ask, let me know if there are still questions!

**Comment by yih-wang** [comment]
@catrobson Thank you for clarifying the issue. I have one more question. As the dropdown can show parent/child relationship, when user select the parent node, will all the children nodes be selected?

**Comment by catrobson** [comment]
Great question!  I think that is probably ideal that it would select all children children nodes by default.  Maybe when we build the control that can be an option for the developer given the situation it is being used in to set to default select children or not.  @dlabrecq - what do you think about making this configurable?

**Comment by dlabrecq** [comment]
Unless that level of configuration is a requirement, I would opt to keep it simple. That is, selecting a parent would select all children by default. 

The more features a component must support, the trickier it will be to implement. For example, if there are multiple parents and different config options for each subset of children?

It's doable, but could be extra logic to implement and maintain unnecessarily? It's also possible to add configuration properties later, to change behavior, should we decide otherwise.

**Comment by catrobson** [comment]
@dlabrecq thanks for the insight.  We'll stick to selecting a parent selects its children for now then.

**Comment by yih-wang** [comment]
Thanks @catrobson @dlabrecq , I designed the function in the simple way (selecting a parent would select all children). You can review the design here: https://redhat.invisionapp.com/share/MECYL572D Feel free to leave comments in both InVision or Github.

**Comment by catrobson** [comment]
Marking this done, I don't think there are any more design tasks here until we get into any implementation support.
