### ISSUE TITLE
Set up individual feature toggles on user profile

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#546]
As a user of OSIO, I would like to turn on and off certain experimental features.

Criteria:
- Wireframes completed
- Any visual designs completed to support wireframes

**Comment by mindreeper2420** [comment]
@catrobson should this be in context of the current screen/layout, or by the creation of a Settings area?

**Comment by catrobson** [comment]
The requirements are these settings are unique per user.  If you feel that we should modify the user profile page to adapt this capability in some new way let's investigate it as an option.

**Comment by mindreeper2420** [comment]
added link for the InVision design to the Platform Designs page: https://github.com/fabric8-ui/fabric8-ux/pull/557

**Comment by mindreeper2420** [comment]
designs can be found here: https://redhat.invisionapp.com/share/EPCQN9YAC

**Comment by mindreeper2420** [comment]
Breaking this out into current design and advanced design.
