### ISSUE TITLE
Design Notification Emails

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#559]
Currently, there are 4 different types of notification emails with individual templates. Basic templates already exist, but were not run through the UXD process. As such, these templates need to be reviewed and updated accordingly.

**Work Item Created**
<img width="654" alt="screen shot 2017-07-28 at 11 40 35 am" src="https://user-images.githubusercontent.com/4032718/28724898-adfa0bac-7389-11e7-8fe5-92237e7e64b6.png">

**Work Item Updated**
<img width="651" alt="screen shot 2017-07-28 at 11 41 34 am" src="https://user-images.githubusercontent.com/4032718/28724912-be091ac4-7389-11e7-94d2-64b45ffbfe50.png">

**New Comment**
<img width="655" alt="screen shot 2017-07-28 at 11 38 49 am" src="https://user-images.githubusercontent.com/4032718/28724840-6b004d16-7389-11e7-8d14-ac9a4ed2df34.png">

**Comment Updated**
<img width="651" alt="screen shot 2017-07-28 at 11 39 59 am" src="https://user-images.githubusercontent.com/4032718/28724870-8a5c4d90-7389-11e7-87dd-383c4b5601c2.png">

----

Follow-Up:
* Update template code with new designs

**Comment by catrobson** [comment]
Related to https://github.com/fabric8-ui/fabric8-ux/issues/559

**Comment by mindreeper2420** [comment]
Related to https://github.com/fabric8-ui/fabric8-ux/issues/432

**Comment by mindreeper2420** [comment]
Current Emails:

**New Work Item:**
<img width="654" alt="newworkitem" src="https://user-images.githubusercontent.com/4032718/28779844-a20aec30-75d2-11e7-8840-61bffac1d87c.png">

**Status Updated:**
<img width="654" alt="statusupdated" src="https://user-images.githubusercontent.com/4032718/28779858-ac5dba5a-75d2-11e7-98c5-10546cc6f363.png">

**New Comment:**
<img width="656" alt="newcomment" src="https://user-images.githubusercontent.com/4032718/28779870-b55f7a1c-75d2-11e7-9171-560597b04811.png">

**Updated Comment:**
<img width="654" alt="updatedcomment" src="https://user-images.githubusercontent.com/4032718/28779875-bb85551a-75d2-11e7-832d-f7d7c8979211.png">

**Comment by mindreeper2420** [comment]
Current Available information via API:
- Creator Name
  * `{{workItem.relationships.creator.data.attributes?.fullName}}`
- Creator Profile Picture
  * `{{workItem.relationships.creator.data.attributes?.imageURL + '&s=20'}}`
- Assignee Name
  * `{{workItem.relationships?.assignees?.data[0]?.attributes?.fullName}}`
- Assignee Profile Picture
  * `{{workItem.relationships?.assignees?.data[0]?.attributes?.imageURL + '&s=20'}}`
- Created Date
  * `{{ workItem.attributes['system.created_at'] }}`
- Updated Date
  * `{{ comment.attributes['created-at'] }}`
- Comment
  * `{{ comment.attributes.body }}`
- Comment Creator
  * `{{comment.relationships['created-by']?.data?.attributes?.fullName}}`
- Comment Creator Profile Picture
  * `{{comment.relationships['created-by']?.data?.attributes?.imageURL}}`
- Status
  * `{{workItem.attributes['system.state']}}`
- Work Item Type (text and icon)
  * `{{workItem.relationships?.baseType?.data?.attributes?.icon}}`
  * `{{workItem.relationships?.baseType?.data?.attributes?.name}}`
- Work Item Title
  * `{{ workItem.attributes['system.title'] }}`
- Work Item Description
  * `{{ workItem.attributes['system.description'] }}`
- Area Name
  * `{{workItem.relationships?.baseType?.data?.attributes?.fields['system.area']?.label || 'Label'}}`
- Iteration
  * `{{workItem.relationships?.baseType?.data?.attributes?.fields['system.iteration']?.label || 'Label'}}`

**Comment by catrobson** [comment]
@zhutaoredhat - just wanted to point out that this is a separate issue from the notification drawer that is a higher priority than the drawer itself.  We want to design the actual e-mails that users receive to better call out what the e-mail is actually about for the user to quickly glance at, understand the change in the system, and take action on if needed.

**Comment by zhutaoredhat** [comment]
@catrobson Thanks for your reminding. I created some new demos.

1.Work item created
![r1](https://user-images.githubusercontent.com/13375283/29160925-c2291804-7de6-11e7-822c-53df28f4407e.png)

2.Work item status updated
![r2](https://user-images.githubusercontent.com/13375283/29160920-c20cd5e0-7de6-11e7-84a6-09f585e56503.png)

3.New comment
![r3](https://user-images.githubusercontent.com/13375283/29160921-c20dcd24-7de6-11e7-93ab-0923166d6f21.png)

4.Comment updated
![r4](https://user-images.githubusercontent.com/13375283/29160924-c228331c-7de6-11e7-9fec-079ddd0716e3.png)

5.Mentioned sb. (The creator will receive all the events no matter mention him. The collaborator would receive the comment mentioned him.)
![r5](https://user-images.githubusercontent.com/13375283/29160922-c2268abc-7de6-11e7-950b-1a392f4d4d74.png)

6.New assignee 
![r6](https://user-images.githubusercontent.com/13375283/29160923-c226c888-7de6-11e7-9e6a-e28e4e369f03.png)

Email notification template
![r7](https://user-images.githubusercontent.com/13375283/29162995-a7cc3336-7ded-11e7-9460-b19cf54a6d61.png)
The current six templates do not cover all requirements. Other templates could be added with the same rules.

**Comment by catrobson** [comment]
@zhutaoredhat Thanks!  A couple of questions and comments:

For create new work item, we usually show work item type with an icon as well, it would be nice to incorporate the icon for easy recognition here.

For the "New Assignee", do you think we should show the old assignee (whether it was unassigned or previously assigned to another user)?

Also, I know this wasn't in the original requirements but do you have any thoughts or suggestions on the e-mail titles for each of these?

**Comment by zhutaoredhat** [comment]
@catrobson 
With icon will be much better and clearer, great suggestion!
Updated create new item
![r11](https://user-images.githubusercontent.com/13375283/29204025-085bbdfc-7ea7-11e7-92c9-a2849b58bdd2.png)

Assignees update (I am not sure the final design of assignees will be in one line or one row, keep consistent with the userface will be well) 
![r12](https://user-images.githubusercontent.com/13375283/29204055-473ecc8a-7ea7-11e7-8285-669ac9181421.png)
![r13](https://user-images.githubusercontent.com/13375283/29204054-473807ce-7ea7-11e7-923d-80b833c43c3b.png)

The email title:
Openshif.io [Workitem 112] Import source archive from local storage

The content part we can see the short story part. eg.
Tzhu commented in the workitem - Workitem 112 [Spacename1] ....

**Comment by catrobson** [comment]
You can only have 1 assignee on a work item, so I think we can just use your horizontal suggestion.  In the future work items will have collaborators and followers where we can have multiple, but not a concern for right now.

**Comment by catrobson** [comment]
@zhutaoredhat I think these are generally looking great!  Can we get these designs into InVision for future reference beyond this issue?

**Comment by zhutaoredhat** [comment]
@catrobson Sure, I had updated it to invision.~ https://redhat.invisionapp.com/share/XHD0O8A5B

**Comment by catrobson** [comment]
Excellent, thanks @zhutaoredhat!  I'm going to close this issue, and we have a new issue (#594) defined for implementation.
