### ISSUE TITLE
Spaces Design

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#572]
In OpenShift.io, spaces are a concept that is encompassing of work items, source code, build definitions, deployment environments, etc. It is the highest-level container for all development artifacts related to the creation of the solution -- where the solution can span multiple code bases, executables, deliverables, releases, etc.

Typically, a user would be added to a space by either creating it, or by being added as a collaborator of that space by someone authorized to do so.  Most of the time, I only care to see my spaces and the spaces that I am collaborating on.  Just as with GitHub organizations, I might jump around these spaces if I am working on many different projects, but once I'm working on a certain thing, I often don't jump between these.  I also am often brought into the context of a space through internal or external paths, such as by clicking on a work item or recent activity change on my personal dashboard, a e-mail notification sent to me about one of my spaces, or a direct link from a colleague.

However, on occasion, I do want to be able to view just a simple view of all the spaces.  For this view, it is likely most useful to have a default "filter" that only shows me those spaces that I own or I am a collaborator in.  However, I should be able to expand out to search all the public facing spaces available for me to view.  I could easily go view items without being a collaborator in these spaces.  For an parallel example, maybe I go look at the PatternFly github repo, but I'm not a collaborator/contributor.  I should still be able to find that repo, but it isn't really part of my default views if I don't work on that project often.

**Verification criteria:**
* Wireframes that capture a way for users see spaces
* The page defaults to showing only those spaces I own or that I am collaborating on
* The user has a way to search and find a space within all the public spaces in the system
* The user should be able to add spaces
* The user should be able to delete only the spaces that they own
* The user should be able to remove themselves as a collaborator from spaces that they are collaborating on

**Existing context:**
Today we have the following screen, and I have with notes of what isn't working below the screenshot.
![image](https://user-images.githubusercontent.com/3739227/28851955-d212b2ce-76f3-11e7-9e9d-4aa16810b03c.png)
* The user navigates by going to "View all spaces" in the context dropdown.  The terminology used here might need to change, but the placement is probably fine
* The context menu switches to my username.  This probably doesn't make sense, and we should have something else shown here.
* The user's profile picture and information is shown on this screen.  This doesn't make sense and should be removed.
* By default, the user sees only the spaces that they created.  This is too limiting, and they should probably see the spaces they created AND the spaces they are collaborating on
* The search at the top of the page then searches all spaces and overwrites the list below with the results, but it isn't clear that this is what you can do with this box at all at a glance.
* Generally PatternFly and design standards have not been applied to the screen and should be

**Comment by junezhang** [comment]
@catrobson 
Hi, Catherine, I made a design proposal here: https://redhat.invisionapp.com/share/Z4CX4QKF2#/247377056_My-Space

![my-space](https://user-images.githubusercontent.com/701009/29023114-e4765ba0-7b9e-11e7-82cc-7cbadb216130.png)

My-Space:  The user navigates by going to "View all spaces" in the context dropdown, the terminology I update to "Spaces"? (Need suggestion?) 
In this page, It lists the spaces those I own and I am a collaborator in. If I'm the owner, then I can edit or delete the space by clicking the kebab menu, the dropdown items are Edit and Delete. If I'm the collaborator, then I can disable my collaborate ability by clicking the collaborator kebab menu, the dropdown item is "Disable my collaborator ability"(Need Suggestion for the terminology?). The actions for owner and collaborator are different.

![expand-collaborator](https://user-images.githubusercontent.com/701009/29023152-0d19ad8c-7b9f-11e7-9ef2-1fbb2eed58fb.png)
Expand-collaborator: As a space should have only one owner, but it may have multiple collaborators. if there are multiple collaborators, we just list one name here, and collapse others.  the backend needs to check if the current user is in the collaborator list, if yes, then list the current user in the first of the order. Click the caret then expand the collaborator list.

![view-all-public-space](https://user-images.githubusercontent.com/701009/29023437-33b4a1a8-7ba0-11e7-9c84-87cbeae7cc81.png)
Click the button of "View all public space", then the active filter changed to "Status: Public", all the public space will overwrites the list of space.

Please help to check the designs, and leave comments.

**Comment by catrobson** [comment]
Thanks @junezhang.  I left some comments in the InVision doc.  Also some here:

"The user navigates by going to "View all spaces" in the context dropdown, the terminology I update to "Spaces"? (Need suggestion?)"
Maybe 'All Spaces'

"the backend needs to check if the current user is in the collaborator list, if yes, then list the current user in the first of the order. Click the caret then expand the collaborator list."  Added comments in the InVision file - we probably usually have too many collaborators for this.  I think just showing the # of collaborators is more scalable.  Maybe we can visually distinguish those that I collaborate on vs. those I don't in some way?

"Click the button of "View all public space", then the active filter changed to "Status: Public", all the public space will overwrites the list of space."  I missed this interaction at first.  I like the concept but wonder if there are other ways to do this for interaction patterns that might be more obvious?  Maybe a toggle switch, tabbed layout, or just rely on the filters?  Not sure the best solution!

**Comment by junezhang** [comment]
HI, @catrobson, I updated the designs, the invison link is here: https://redhat.invisionapp.com/d/#/projects/prototypes/11721510


![my-space](https://user-images.githubusercontent.com/701009/29115592-c1d011ee-7d2a-11e7-9b66-8791d0db03e0.png)

1, Update the content items of the list view:

- Status icon - this column is the Space status: Public, Private
- Space Name & Description  - click the space name, it will link to space detail page.
- num of collaborators - How many collaborators in this space
- num of work items - how many work items in this space
- Last Update - Using the format as how many hour ago, and how many days ago, looks like 3hours ago, 3days ago, when more than a month, it will list the exactly date like "2017-01-01"
- Label for collaborator or owner - this column is to show the current user is the space's Collaborator or Owner.
- Action button - If user is owner, then the button is Delete. if the current user is collaborator, then the button is "Remove me as collaborator"

2, Button Group for "View My Space" and "View All Public Space"
Beside the filter, there are two quick filter buttons: view my space, view all public space.
When into this page, the button of "View My Space" will be selected by default. the content of the list is all my space that I own and collaborate.
When clicking "View all the public space", it will list all the public space. If click the "View my space", then it list my spaces.

3, Filter
Add categories to filter, it is easier for user to search some special items. Such Collaborator include me or Status is private. 
One example: when typing "Application" in the filter box, and then press Enter or click the magnifier icon, it will list all the items related application. and below the search there is "Active Filter". at this moment, "View my space" and "View all public space" are unselected style.

I haven't added annotations to the design, want to have a discuss with you first. Welcome any comments. Thanks.

**Comment by junezhang** [comment]
![my-space-update-note](https://user-images.githubusercontent.com/701009/29451376-07045174-8435-11e7-9f88-af8ab962d31e.png)

@catrobson  I've re-updated the space design like the attachment.
The list is ordered with Last Update by default. Because Last Update is common for "My space" and "View all space". if using Last visited, I'm afraid in all space, some spaces don't have the Last Visited data.
but user can change it through the order button(annotation #4).
In the dropdown menu, the type of order is Last Update, Last Visited, Create Time, # of Collaborators, # of work items. 
How do you think about it?
