### ISSUE TITLE
All caps used for OpenShift.io Logo, shouldn't it be OpenShift.io?

### ISSUE THREAD

**Issue by Preeticp** [fabric8-ui/fabric8-ux#574]
Moving Issue from Fabric8 UI to here as directed. (https://github.com/fabric8-ui/fabric8-ui/issues/1826#issuecomment-319891244)
OpenShift is always written with only O and S in capital case, but in the logo we have it as OPENSHIFT.io. This is not consistent with our usage of OpenShift.io in all the other places. The logo afaics is seen on the landing page before login, on the login page and post login. I have attached a couple of screenshots below for reference.
![2nd instance of wrong case](https://user-images.githubusercontent.com/16647625/28916722-d35ebf1a-7860-11e7-835d-ce7f94e819d2.png)
![case for openshift not in sync](https://user-images.githubusercontent.com/16647625/28916723-d3614f82-7860-11e7-9b8b-9c84ed6cb160.png)

**Comment by Preeticp** [comment]
@mindreeper2420 I am not sure this is the right repo to raise this issue. I was directed here, please let me know if this should be raised some other place

**Comment by mindreeper2420** [comment]
@preeticp I believe these were given to us right from Brand, but I will verify. It is not uncommon for the logo to be displayed one way and written out to be another.

**Comment by Preeticp** [comment]
I see what you mean @mindreeper2420 I see the logo is standard for OpenShift, for example: https://www.openshift.com/
Feel free to close the issue if you think it is alright. I just felt it was inconsistent at different places on the OSIO

**Comment by catrobson** [comment]
@Preeticp, @mindreeper2420 These are the logos provided to us by Brand, and the fact that the logo itself is all caps while written in paragraph text it is mixed case is correct to follow our brand standards.
