### ISSUE TITLE
Account Clean-up

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#581]
How do we allow administrators to clean up accounts?  

* Gathering requirements
* Create simple designs for quick implementation during first round

Also note that OpenShift Online will be locked down for users of OSIO moving forward.

**Comment by catrobson** [comment]
Requirements I got about the designs for this today from @joshuawilson:

* Status dropdown should show OpenShift tenant resource utilization/quota. 
** [Notes from Cat: from the system this is a % of full.  The % can translate to green, yellow, red that bubbles up to the top level for the overall status, but I think we should ideally be using the donut chart in the status dropdown to show the actual percentage.  This means a bit of a deviation from the current design but I think heads towards a more useful status dropdown over what we have today.]
* Clicking on the % in the status dropdown should take you into a detail page that shows all the different objects that are impacting the quota.  [Note from Cat:  I think this belongs as a new area in Settings called something like "Account Quotas" to align it to the OpenShift naming]
    **  Namespaces
    **  Resources
    ** Other?  Need to investigate further, once we have an initial design together we can gather this detail from KB.
* Can click through this list to go to OpenShift to manage/shut down/etc these items, we don't need the controls right in OSIO for that.
* Also enable a Clean button here that allows the user to wipe clean all of their OpenShift projects and revert them to default state.  Need to clean up all the spaces that the user owns as well at this point.  Right now everyone can see this and use it, so we need some heavy warnings.  In the future only Administrators will get this functionality with we add permissions.  [Note from Cat:  The design pattern where you have to type some sort of text in for validation before proceeding might be appropriate here since it is such a severe action]
* All of this action of deleting things won’t touch the user's GitHub accounts and we should let them know that any code on GitHub will be safe.

**Comment by mindreeper2420** [comment]
Design Link: https://redhat.invisionapp.com/share/6FCY2KWZR

**Comment by mindreeper2420** [comment]
Update to the Horizontal Navigation to include an OpenShift Quota status:
![resources](https://user-images.githubusercontent.com/4032718/29085669-f2c0bc74-7c3d-11e7-877f-cca8bceafe13.png)

**Comment by catrobson** [comment]
@mindreeper2420 - I didn't see the "Clean Account" button in these designs so far.

**Comment by mindreeper2420** [comment]
@catrobson that will be in the next update. I've been working my way down the list.

**Comment by catrobson** [comment]
@mindreeper2420 - OK, thanks.

**Comment by mindreeper2420** [comment]
@catrobson I've added the first pass at the Clean process, along with an updated quota navigation display. I'll add comments and steps next.

**Comment by mindreeper2420** [comment]
@catrobson The wireframes have been updated with new terminology and the completed process. I tried to show cases when everything has been erased vs when there was an error in the process. I will add detailed call outs to help clear up these actions.
