### ISSUE TITLE
WIREFRAMES: Refine page level components 

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#583]
- Flesh out more of the detail of the components featured in the current wireframes for Hypothesis
-  Do some research on living documents and task lists and see what can be applied to Hypothesis

**Comment by catrobson** [comment]
@lwrigh can you link in your work (research docs, wireframes) and close?

**Comment by lwrigh** [comment]
Yup I can do that this morning.

**Comment by lwrigh** [comment]
Research doc for living documents and progress bars: https://docs.google.com/a/redhat.com/document/d/1sYVmhjyfZgM7QS790t9PXfFkSuTSs_VwBQO_54-uf6c/edit?usp=sharing

PDF: 
[Hypothesis- August 11 2017.pdf](https://github.com/fabric8-ui/fabric8-ux/files/1222568/Hypothesis-.August.11.2017.pdf)

Invision: https://redhat.invisionapp.com/share/2ED0XG17N#/244995481_First_Time_UX-_Dashboard
