### ISSUE TITLE
Way to see the collaborators in a space as a collaborator/viewer

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#587]
If I am a collaborator or viewer of a space, I should be able to see a list of all the collaborators of that space.  Right now only owners can see the collaborators.

**Comment by catrobson** [comment]
I should also be able to see who the owner of the space is.

**Comment by deernano** [comment]
@catrobson 
This is the View all collaborators workflow:
The collaborators/ owner / viewers could click the kebab menu and then click "view all collaborators" to enter the collaborators tab and view all the collaborators.
The collaborators/ owner / viewers could also click the icon on the header and then click "Collaborators" tab to view all the collaborators. 
![view-collaborators](https://user-images.githubusercontent.com/5396309/29872301-a7f76914-8dc1-11e7-94db-c92936f2b1ab.png)

Please review the workflow. 
Other things:
1. When hover the icon on the header, I think we could have a tooltip to tell users what the icon is. Currently, users cannot figure out what the icon is and what content within the that page. 
2.If we want the viewer and the collaborator to view all collaborators of a public space, we should open their permission to access the "all collaborators" page, this workflow is based on the situation that they already have the permission.
3. Currently, reviewers do not know that they have been added as a collaborators of a space. For example, if I add June as a collaborator and mzhongtest1, she will not get a notification or an email to know. Do we have any concern on this?

**Comment by catrobson** [comment]
@deernano Thanks!  The right hand side of that flow, wher ethe user can click on the settings icon, is only available to Space owners.  Collaborators/Viewers of that space won't ever see the settings icon in their navigation.  (For instance, try going to https://openshift.io/openshiftio/openshiftio).  Viewing collaborators via the kabob makes sense, but then where would this put you in the overall navigation?

For your other questions:

> When hover the icon on the header, I think we could have a tooltip to tell users what the icon is. Currently, users cannot figure out what the icon is and what content within the that page.
Agree!  @mindreeper2420 is this something that would be easy to add?  The tooltip should say "Space settings".

> If we want the viewer and the collaborator to view all collaborators of a public space, we should open their permission to access the "all collaborators" page, this workflow is based on the situation that they already have the permission.
I think we can make the page something that we could show in the context of the space settings, or outside of the space settings, but I don't think that we want to allow any user to see the space settings area.  This should be reserved for owners (and in the future Admins as well).   The "view" version of the page also shouldn't let the user add collaborators, just view them.

> Currently, reviewers do not know that they have been added as a collaborators of a space. For example, if I add June as a collaborator of mzhongtest1, she will not get a notification or an email to know. Do we have any concern on this?
Yes, I think this would be a good idea to capture as part of this story so we can work on adding a notification around this!

**Comment by deernano** [comment]
@catrobson The wireframe has been uploaded to Invision. Please review it. Thank you!
https://redhat.invisionapp.com/share/GMDAF50Q7#/251301582_Collaborators0

**Comment by catrobson** [comment]
@deernano The updated wireframes look great!  Closing this issue and we'll reach out if anything comes up during implementation.
