### ISSUE TITLE
WIREFRAME:  Pipeline choice design

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#588]
When choosing a pipeline, the user should get a list of pipelines available to them and be able to understand which pipeline will perform which actions.  The user can then select one pipeline to proceed forward with.

This design will be used in the wizard and in hypothesis.

Verification Criteria:
* Wireframes captured
* Reviewed with UXD & Joshua + Corinne
* Shared with Corinne, captured in Hypothesis wireframes for future implementation

**Comment by lwrigh** [comment]
@catrobson Can you attach the photo of the whiteboard sketch from Friday if you have it?

**Comment by catrobson** [comment]
Oh right!  Thanks for the reminder.  Here it is.
![img_2836](https://user-images.githubusercontent.com/3739227/29278365-839c7550-80e2-11e7-8587-de34ca4a7406.jpg)

**Comment by lwrigh** [comment]
![screen shot 2017-08-14 at 5 01 24 pm](https://user-images.githubusercontent.com/20227374/29291655-49321f02-8112-11e7-89e4-71c4eb578a2d.png)

The description of the pipeline could be featured underneath of the name of the pipeline before it is expanded. Once it has been expanded, more information about the pipeline and its different stages can be accessed. @catrobson What do you think of these so far?

**Comment by catrobson** [comment]
I'm not sure I'm following the # of branches column, not sure how that relates to the pipeline.  I think the one with the description in the collapsed version of the row will work best to help users identify the right pipeline.  We probably don't need the label "Description:" and can just show the description.  The fold of of just the visualization and the hover as you show I think works well.

**Comment by lwrigh** [comment]
@catrobson Here's an updated version of the pipeline component: 

![screen shot 2017-08-15 at 1 41 36 pm](https://user-images.githubusercontent.com/20227374/29328175-a1a2d9a8-81bf-11e7-8818-838b605c4955.png)

I got rid of the description label. the branch column, and adjusted the spacing a bit.

**Comment by catrobson** [comment]
Can we also get rid of the header in the dropdown and just show the visualization?  Since it is in the context of the row that already has a header this seems redundant.

**Comment by lwrigh** [comment]
@catrobson 
Here's the latest version: 
![pipelines componet for the space wizard and hypothesis](https://user-images.githubusercontent.com/20227374/29332593-876e6e4e-81ce-11e7-804c-ed89e3f07d89.jpg)


Invision Link:  https://redhat.invisionapp.com/share/W7D1RG2DU#/248763313_Pipelines_Componet_For_The_Space_Wizard_And_Hypothesis

**Comment by lwrigh** [comment]
*Updates in the future will include an overlay that describes the environment that the stage lives in
