### ISSUE TITLE
RESEARCH: Attend user workshops & gather feedback

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#593]
Attend Burr, Brad, and Rapheal's user workshops.  Gather feedback highlights and insights and share with UXD team and other major stakeholders.  We'll also want to roll up information from many sessions to send to whole OSIO team, but this can be another story.

**Comment by Essjaysee** [comment]
2 additional workshops this week.

**Comment by Essjaysee** [comment]
Still attending, some stories were created as a result of the feedback/insights gathered: #648, #650, #651.

**Comment by Essjaysee** [comment]
Ongoing...

**Comment by Essjaysee** [comment]
None scheduled for last week (Java One) or this week.

**Comment by Essjaysee** [comment]
Workshops are done for now, with the advent of the self-service document.
