### ISSUE TITLE
Codebases and Workspaces wireframes

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#599]
Stevan Lemur created a first version of codebases and workspaces designs here:  https://redhat.invisionapp.com/share/94CH0VNV5

The user goal is to code, and we want to look at collapsing all of this information into one tab that focuses on the user task, Coding.

This story is to do a wireframe pass that meets the following criteria:
* Users can view their codebases and the branches of those codebases.
* Users can see the workspaces associated with each codebase and branch
* Users can add and remove codebase links (these are links to github repos)
* Users can add or remove workspaces
* Users can open existing Che workspaces from seeing the workspaces available, or from looking at their codebases and branches and the workspaces associated with them.

Note that the existing wireframes can be used a reference for the types of information needed, but we want to move towards 1 tab for all the information, and move away from using modals in the OSIO workflows as much as possible - leaning towards full page dedicated tasks for users to focus on.

Current thinking is that we could have a view switcher on a "Code" tab that transforms the view based on whether you think in terms of your codebases or your workspaces.  Default would be codebase.  Open to other design alternatives.

**Comment by slemeur** [comment]
I'll be glad to join the discussions on this issue.

**Comment by catrobson** [comment]
@slemeur thank you, we'll loop you in and I expect you'll see updates on this issue.  @zhutaoredhat - you can find @slemeur's sketch file to work from here if you find that helpful:  https://drive.google.com/drive/folders/0B_zZwzicsCVzU2h3UnZ2R2JMQ1U

**Comment by zhutaoredhat** [comment]
Thanks @catrobson @slemeur 
I had created a mockup today and met some questions:
![a1](https://user-images.githubusercontent.com/13375283/29410606-cee313cc-8383-11e7-83ca-be4c123def78.png)
1.The branches are created in github and then OpenShift sync the data?
( Get some answer form Stévan:
there are different branches:
- remote branches
- local branches
Remote branches are on github - developers can create the branch on github or other tools
Local branches can be created in a workspaces on openshift.io
you are making a good point. 
It is also possible to create multiple local branches in a workspaces.
which could be confusing
I think we should only refer to the remote branches)
2.About "Users can add and remove codebase links (these are links to github repos)"
 is this means a codebase could connect many github repos?
![image](https://user-images.githubusercontent.com/13375283/29410766-a4c02fd4-8384-11e7-8468-8972acccab97.png)

**Comment by catrobson** [comment]
@zhutaoredhat - Just referenced this issue from feedback we were getting on the current design.  The github icons are not serving any purpose right now, every row would have the same github icon at the front.  Therefore I think we can remove this completely.

Regarding branches, I agree that we should only be displaying remote branches, not local branches.

For linking to github URLs, no I think the intent here should be that 1 codebase = 1 github repository.   The main link of the row "che-samples/web-java-spring-petclinic" in your case would the the single link to that github repo.  Users can remove a codebase, which just removes the link in OpenShift.io to that github repository, but would not actually delete the repository on Github.  Users can add a codebsae, which would add a new overall row to the list view.

**Comment by zhutaoredhat** [comment]
Sure, got it, thank you @catrobson  I will update it tomorrow~

**Comment by zhutaoredhat** [comment]
@catrobson @slemeur Updated the mockups here https://redhat.invisionapp.com/share/DUD3GQZGM. Open to feedback!~

**Comment by zhutaoredhat** [comment]
@catrobson @slemeur Thanks for your feedback last week. Please review the Aug.21 updated part. https://redhat.invisionapp.com/share/DUD3GQZGM
I had try the pattern of Compound Expansion before. Not feels very well.
Today's update is a full page design~

**Comment by zhutaoredhat** [comment]
@slemeur @catrobson The mockups had been updated. https://redhat.invisionapp.com/d/main/#/projects/prototypes/11815599 Hope make sense to you.

**Comment by catrobson** [comment]
@zhutaoredhat thanks for making the updates to this!  Can you post your design files to InVision so we can use them for the visual design pass?

**Comment by zhutaoredhat** [comment]
@catrobson I had try to post the design files to Invision, but it does not support .sketch file now , even use Craft which just pull the .png files to invision. So I pulled the file to the google drive. Here is the link:
https://drive.google.com/drive/folders/0B_zZwzicsCVzU2h3UnZ2R2JMQ1U

**Comment by joshuawilson** [comment]
@zhutaoredhat how do I view those designs? As a developer I need to see them to build it. :)

**Comment by gorkem** [comment]
@ashumilova are you aware of these?

**Comment by catrobson** [comment]
Hi @gorkem @joshuawilson - this was an effort to initially design out this area.  We need to do full review with engineering on this still, so most people probably not up to speed on them.  It would be great to identify a team we could walk through these with in the next two weeks though!

**Comment by joshuawilson** [comment]
@catrobson this should be reviewed with @ashumilova, anyone from her team, and myself. (and @gorkem if he wants)

**Comment by zhutaoredhat** [comment]
Hi @joshuawilson I would like to share a link to you~ https://redhat.invisionapp.com/share/U2D95C1EC

**Comment by joshuawilson** [comment]
Thanks @zhutaoredhat. I am able to view those.

**Comment by zhutaoredhat** [comment]
@joshuawilson You are welcome~
