### ISSUE TITLE
WIREFRAME:  Experiment definition and ready to run pages merged into one page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#600]
After discussions this last week, look to wireframe how we could have an experiment definition page that has the layout/design of the ready to run page brought into it, and these two pages are collapsed into one.

Then, the user would start with an empty state of an experiment definition, and as they work through the items they need to define they would check off, eventually resulting in an experiment that is "ready to run" - but not bringing them to a separate page.

**Comment by lwrigh** [comment]
Invision Link: https://redhat.invisionapp.com/share/Y9D61YCX2#/249650842_Experiment_Definition_And_Ready_To_Run_Title_Page
