### ISSUE TITLE
WIREFRAME:  Hypothesis details page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#601]
Wireframe what the hypothesis details page would look like once the user has already defined the hypothesis, and experiments are running or have been defined against this hypothesis.

**Comment by lwrigh** [comment]
[Hypothesis Details Page- Multiple Experiments Copy.pdf](https://github.com/fabric8-ui/fabric8-ux/files/1252799/Hypothesis.Details.Page-.Multiple.Experiments.Copy.pdf)
[Hypothesis Details Page- Multiple Experiments.pdf](https://github.com/fabric8-ui/fabric8-ux/files/1252798/Hypothesis.Details.Page-.Multiple.Experiments.pdf)
[Hypothesis Details Page- One Experiment.pdf](https://github.com/fabric8-ui/fabric8-ux/files/1252800/Hypothesis.Details.Page-.One.Experiment.pdf)

**Comment by lwrigh** [comment]
Invision Link: https://redhat.invisionapp.com/share/X4D6V5HT8#/250252689_Hypothesis_Details_Page
