### ISSUE TITLE
RESEARCH:  Define three user scenarios for Hypothesis

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#603]
Define three user scenarios that we can use to base our user script, testing, and screen mockups on.

Scenario 1:  For a stakeholder doing a single experiment against a hypothesis for 1 week
Scenario 2:  For a technical investigator doing many experiments against a hypothesis for 3 months
Scenario 3:  For either stakeholder or technical investigator showing a widely successful experiment

**Comment by dgutride** [comment]
Met to discuss scenarios (I think this is done @Essjaysee - moving to closed as part of planning)
