### ISSUE TITLE
VISUAL DESIGN:  Resource utilization

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#604]
Visual Design pass on the resource utilization screens that Adam has put together here:  https://redhat.invisionapp.com/share/AQD3WV1ZR#/screens

**Comment by mceledonia** [comment]
[Invision project link](https://redhat.invisionapp.com/share/QED5XSUJX) 

- Each screen a different version
- Version C2 seems to be best contender.

**Comment by mceledonia** [comment]
Closing this one
