### ISSUE TITLE
DESIGN:  Launch updates for initial launch - 5PT

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#605]
Update Launch design based on agreed upon changes captured here:  https://docs.google.com/document/d/1hZtn-2n_0xL0u_sugaVqPtLLxDxMb6RyR3bKxu91soE/edit?ts=599731cc#heading=h.srustkltz7f2

**Comment by mindreeper2420** [comment]
**Notes:**
moving to developers.redhat.com/launch (under RHD - Technologies / Accelerated Development and Management)

* New workflow
  - must be logged into RHD to use the Launch product

* From Technologies page, bring to login to Launch splash page (Catherine’s design), click ‘Launch your project, log into RHD, then step process (use OpenShift or get a zip file).

* Remove option for OpenShift vs zip file as first step
   - Make this the last step

* Collapse Mission and Runtime into one screen (two columns, for easy decision). Whether a user wants to go down the Mission path, or base it off of a certain language.

* Health Check Mission is an empty project. This is a ‘start from scratch’ process with nothing predefined.

* Update last step of Zip download next steps to include the Key aspects of the README.adoc in the actual ‘Next Steps’ screen

_Deployment Methods:_
- MiniShift
- Zip
- OpenShift Online
  - if they have an account, automatically recognize and give ability to use seamlessly
  - if they don’t have an account, then should be shown option to sign up for waitlist

**Comment by mindreeper2420** [comment]
InVision Design Link: https://redhat.invisionapp.com/share/XQD7EDSSV
