### ISSUE TITLE
WIREFRAME:  BDD language editor for advanced hypothesis definition

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#616]
Create wireframes around how we could allow technical users to use a BDD language editor for advanced hypothesis definition.

Validation Criteria:
- Wireframes created
- After agreement, fold into overall hypothesis wireframes and invision

**Comment by mindreeper2420** [comment]
InVision design link: https://redhat.invisionapp.com/share/6RD57TPH3
