### ISSUE TITLE
VISUALS:  User profile & settings

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#621]
Visual design for the overall user profile and settings pages that Adam has started building out.

[https://redhat.invisionapp.com/share/C5CWDPFP2](https://redhat.invisionapp.com/share/C5CWDPFP2)

This will include visual design of:
* User profile (view with editing)
* Connected accounts
* Notifications

Resources and Feature toggling navigation pages will be separate visual design stories.

**Comment by bdellasc** [comment]
Added ToC and visual design screens to the [user settings InVision wireframe flow](https://redhat.invisionapp.com/share/C5CWDPFP2)

**Comment by bdellasc** [comment]
Updated all screens based on feedback. There's some new things in there I need folks to look at before I close the story.

**Comment by bdellasc** [comment]
Finished latest round of edits. Will need to figure out with dev how best to get them implemented.

**Comment by bdellasc** [comment]
@mindreeper2420 is working on building the individual pages and I'm providing feeback as he moves through them. Once the vertical nav is ready, those pages can be taken into the overall layout with the nav wrapper.
