### ISSUE TITLE
Dev:  Spaces list view

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#624]
DEPENDENCY:  Spaces list view visual design story - https://github.com/fabric8-ui/fabric8-ux/issues/623

Implement updated space list view.  HTML/CSS and Javascript.  Understand how we can gather the information needed at the list view level. 
* Remove space listing from User Profile
* Will link off of "View all spaces" in contextual dropdown

**Comment by bdellasc** [comment]
[Visual design story](https://github.com/fabric8-ui/fabric8-ux/issues/688) 
[InVision flow](https://redhat.invisionapp.com/share/DQDSL22JA)

**Comment by catrobson** [comment]
Closing this story as there were other stories for building this capability.
