### ISSUE TITLE
Visual Design:  Decide on the gray background color

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#625]
Determine what shade of gray we use for the backgrounds of OSIO.  Coordinate with Adam on CSS updates and pages that need to be updated with this.

* Decide on the color
* Gather a list of pages that should change to this background color
* Coordinate changing those pages with Adam (Adam to create story for implementation if needed)

**Comment by bdellasc** [comment]
Add notes RE: which screens to work on gray BG issue. See notes here:

[https://docs.google.com/a/redhat.com/document/d/1tADY8SGf6edkNphL9HcNbhZEcYUXhjwTEErDVaq1PM4/edit?usp=sharing](https://docs.google.com/a/redhat.com/document/d/1tADY8SGf6edkNphL9HcNbhZEcYUXhjwTEErDVaq1PM4/edit?usp=sharing)

**Comment by bdellasc** [comment]
Added notes to #640
