### ISSUE TITLE
Requirements Gathering:  Space Dashboard

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#628]
Gather requirements about what a user would want to see at the highest levels of a space dashboard by default.  Document for any designer to use for designing an updated page.

**Comment by dgutride** [comment]
@aslakknutsen 

Wireframes here:
https://redhat.invisionapp.com/share/6XD26VFZB#/screens

After looking at the current api's and what the wireframes call out - here is what I think we need.
Current UI uses /namedspaces/{username} to retrieve space list unless they are searching and then it uses spaces?q={searchQuery}

API needs based on UI:
Space retrieval API
  - Changes:
    - API needs to be Searchable/sortable API for retrieving spaces
    - We also need to differentiate between spaces I own, spaces I’m part of and spaces I’m just looking at
 - GET Parameters to support filtering:
   - SortBy (name, # of collaborators, # of work items, creation date, last visited date)
   - FilterBy (name, collaborator/owner, status)
   - Show only my spaces or retrieve all spaces
 - Response properties
   - Total count
   - Name
   - Description
   - Public/Private (not implemented yet)
   - Count of collaborators
   - Count of work items
   - Last visited date
   - Creation date
   - User relationship (Owner/Collaborator/None)

Remove me as collaborator API
 - This is a new link on spaces page to let user leave a space - we’d need an API for this
