### ISSUE TITLE
Discovery: Configurable Dashboards

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#629]
Gather insights about configurable dashboards from other systems out there.  Capture things that work well or don't work well in various configurable dashboards that systems provide.  Understand common patterns and capture common user needs in these environments.

**Comment by gdoyle1** [comment]
I put together a slide deck of research and a set of recommended requirements here : https://docs.google.com/a/redhat.com/presentation/d/1IunnqTMZj2XeuLMmprs678ZLyjdN1MeGGhvMcXfG-Y4/edit?usp=sharing
