### ISSUE TITLE
PF Design Contribution:  Overlay Panel

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#632]
Contribute the OSIO use case of an Overlay Panel.   

General requirements gathering document:
https://docs.google.com/a/redhat.com/document/d/1p03UVQ7NzDtsIneitoeXRmIPzF0aodSMVgfxZiAqgfU/edit?usp=drive_web

Colleen will be contributing overall guidance for these patterns, and the OS overlay panel use case.  We'll be contributing the OSIO use case (you can still interact with content behind the panel).

Follow this style of mark up: 
http://www.patternfly.org/pattern-library/communication/about-modal/#/design

**Comment by lwrigh** [comment]
https://github.com/patternfly/patternfly-design/issues/409

**Comment by lwrigh** [comment]
https://github.com/patternfly/patternfly-design/pull/418#pullrequestreview-62786348
