### ISSUE TITLE
DEV: Platform guidelines

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#637]
Develop a set of platform guidelines for components that integrate with it.  These are guidelines that MUST or SHOULD be met by any component.

There might also be leveling involved, so that components that only meet some of the SHOULD might have different a maturity index to consider which might impact how they are handled by the platform, integration, and deployment processes.

**Comment by dgutride** [comment]
Wrote initial document here:  https://docs.google.com/document/d/1gHDT9qZJYkzERvIIjMMVcNlR2399DQjXlxzPCuRe_gQ/edit - moving to closed as initial set of requirements met.  We should probably capture a story to add guidelines to openshift.io repos along with the team.
