### ISSUE TITLE
Update pages that should have gray backgrounds

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#640]
Based on a conversation with @catrobson:

**Let's try #EDEDED for these pages' gray background**

- [x] Account Home Page (has dark gray) - https://openshift.io/_home
- [x] Space Home Page (has dark gray) - https://openshift.io/_username/_spacename
- [x] Analyze Page
- [ ] Stack Report - Redesigned by Sunil - will get InVision link posted
- [x] Settings > Areas
- [x] Settings > Collaborators
- [x] Plan > Backlog (gray empty state and gray for area below a list that doesn't fill the screen)
- [x] Profile Settings Pages - new visuals not finalized yet (as of 9/1/17) -     [https://redhat.invisionapp.com/share/C5CWDPFP2](https://redhat.invisionapp.com/share/C5CWDPFP2 )

**Hold until new designs are finalized/implemented**

- Spaces Listing Page - "https://openshift.io/_username/_spaces"
 New design being proposed here, visuals pass not done yet -
 [https://redhat.invisionapp.com/share/6XD26VFZB](https://redhat.invisionapp.com/share/6XD26VFZB)

- Create > Codebases - [ttps://redhat.invisionapp.com/share/DUD3GQZGM](https://redhat.invisionapp.com/share/DUD3GQZGM)

- Create > Pipelines

- Create > Applications

- Create > Environments

- Bayesian/Analytics Report - Screenshot here:  [https://drive.google.com/open?id=0B_zZwzicsCVzOF9YV2tSLXRRNDQ](https://drive.google.com/open?id=0B_zZwzicsCVzOF9YV2tSLXRRNDQ)

**Comment by mindreeper2420** [comment]
@catrobson @bdellasc a few questions:

- Stack Report background - is that the Stack Report modal (complete Stack Report) that is shown from the Space Widget?
- Plan (Planner) background - only the list rows will be white, sitting on top of the grey background?

These will have to be split into 3 different PRs, since this work touches Platform, Planner and the Recommender.

**Comment by mindreeper2420** [comment]
**Collaborators:**
<img width="1920" alt="collaborators" src="https://user-images.githubusercontent.com/4032718/30282953-c5ae57e8-96e4-11e7-9055-e1c8ce201dec.png">

**Areas:**
<img width="1920" alt="areas" src="https://user-images.githubusercontent.com/4032718/30282945-c0b78444-96e4-11e7-9ac4-4c6afeb66cea.png">

**Spaces Dashboard:**
<img width="1920" alt="spaceshome" src="https://user-images.githubusercontent.com/4032718/30282941-bbf607be-96e4-11e7-81ce-8882b15aa3d4.png">

**Comment by mindreeper2420** [comment]
Stack Report will not be changed at this time.
