### ISSUE TITLE
DESIGN:  Full page navigation for experiment selections

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#642]
To select a codebase, pipeline, and instrument the user should be brought into a full page experience.  Consider what these should look like and update the wireframes accordingly.

**Comment by lwrigh** [comment]
Selecting a codebase: 
![experiment definition- selecting a codebase codebranch 1](https://user-images.githubusercontent.com/20227374/30227157-a1243b4e-94a6-11e7-989b-c7f101d1979e.png)
![experiment definition- selecting a codebase codebranch 2](https://user-images.githubusercontent.com/20227374/30227158-a130fbe0-94a6-11e7-9a49-7a8e9b91dbab.png)
![experiment definition- selecting a codebase codebranch 3](https://user-images.githubusercontent.com/20227374/30227159-a13fc2b0-94a6-11e7-8443-77ee69e00122.png)

Selecting a a deployment pipeline: 
![experiment definition- selecting a deployment pipeline 1](https://user-images.githubusercontent.com/20227374/30227184-b750a0d8-94a6-11e7-91e6-36dab46dae78.png)
![experiment definition- selecting a deployment pipeline 2](https://user-images.githubusercontent.com/20227374/30227186-b7644f2a-94a6-11e7-9bb2-620594c0518b.png)
![experiment definition- selecting a deployment pipeline 3](https://user-images.githubusercontent.com/20227374/30227185-b751c134-94a6-11e7-8ff2-a30c0ab22583.png)

Selecting a type of instrumentation: 
![experiment definition- selecting an instrument 1](https://user-images.githubusercontent.com/20227374/30227206-cc6244fe-94a6-11e7-835f-5fd9e73a5cf8.png)
![experiment definition- selecting an instrument 2](https://user-images.githubusercontent.com/20227374/30227205-cc615df0-94a6-11e7-8a69-b23d4d77c865.png)
