### ISSUE TITLE
Visual/Design: Sort out status icons

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#648]
Hourglass icon on status drop-down menu is hard to read/interpret.  "Waiting".  This came from the new PatternFly status.

Burr also has a different state for each item in the status dropdown in an issue (need to link).

Consider what a better icon would be for this situation.  Refer to new PatternFly statuses.

**Comment by mindreeper2420** [comment]
Current icons and states in the status menu:
```
const statusCssUnknown = new StatusKind("Loading data", "pficon pficon-in-progress");
const statusCssError = new StatusKind("Error", "pficon pficon-error-circle-o");
const statusCssOK = new StatusKind("OK", "pficon pficon-ok");
const statusCssPending = new StatusKind("Pending", "pficon pficon-pending");
const statusCssContainerCreating = new StatusKind("Creating", "pficon pficon-on-running fa-spin fa-fw");
const statusCssNoResource = new StatusKind("Off", "pficon pficon-off");
```

**Comment by catrobson** [comment]
Also refer to https://github.com/openshiftio/openshift.io/issues/445

**Comment by bdellasc** [comment]
Let's try using the fa-clock (Font Awesome) icon, but at a slightly larger size (approx 16px) to make up for the difference in size between the PatternFly status icons and the fa clock

![fabric8-ux-648 -sortoutstatusicons](https://user-images.githubusercontent.com/17882357/30490065-e831c08c-9a06-11e7-84b4-8fac8b9a3296.png)
