### ISSUE TITLE
HTML/CSS:  Fix work item empty state font

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#653]
The font for the first sentence in the empty state of the My Work Items box is a different font than the other empty state boxes show on the Account Homepage.

![image](https://user-images.githubusercontent.com/3739227/30122858-ec29352c-92fd-11e7-8b70-bf315ee9f292.png)

**Comment by catrobson** [comment]
Can we also change the text on the "recent active pipelines" widget empty state from "No recent failed or active pipelines" to "Pipelines reflect the integration and deployment stages your code will go through."
and from "Failed pipelines or active pipelines will display here when you commit and build your codebase" to "Pipelines will display here when you commit and build your codebase."

**Comment by junezhang** [comment]
@catrobson please help to check the attachment. is it right?
<img width="1374" alt="screen shot 2017-09-07 at 4 46 33 pm" src="https://user-images.githubusercontent.com/701009/30154347-38700c5a-93ec-11e7-82e7-cb3f74739529.png">

One concern about the capitalization. In openshift.io project, all the headline style, capitalize the first letter of the title. 

1. `Create a Space` is different with others. Should I update it to "Create a space"?
2. The capitalize way is different with PatternFly. the following is the PatternFly Headline Style Capitalize Guideline:

> Headline style
> For headline style, capitalize the first letter of every word except for articles (a, an, the), coordinating conjunctions (and, but, or), and prepositions of three letters or fewer (of, on, by, in). There’s one exception: Any word that is the first word in the headline or the last word should be capitalized, regardless of its part of speech. For example, “Where to Install”

**Comment by junezhang** [comment]
@catrobson I've updated the capitalization like the below picture:
![screen shot 2017-09-08 at 4 26 16 pm](https://user-images.githubusercontent.com/701009/30202891-98e31cf0-94b2-11e7-8b55-3082de7cac77.png)

**Comment by catrobson** [comment]
@Essjaysee What do you think?

**Comment by Essjaysee** [comment]
Capitalization looks great, thanks!  Just a couple other little things:

- Add a period to the end of the sentence "Learn how to get started in the documentation"
- Remove the period from "Work items reflect the work..." in the middle card
- Reword the second sentence in the middle card to "Once you create or join a space, work items that you create or are assigned to display here."
- Reword the first sentence in the right-hand card to "Pipelines reflect integration and deployment stages that code goes through"
- Remove "will" from the second sentence in the right-hand card

**Comment by junezhang** [comment]
The PR has been merged. so close this issue. if anything needs to update, please re-open it.
https://github.com/fabric8-ui/fabric8-ui/pull/1988
