### ISSUE TITLE
HTML/CSS:  Fix header on Areas, Collaborators

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#654]
The alignment of the add button on Collaborators and Areas pages is too close to the header bar.  There is also an additional header that is not needed given the phrase above the list view on these pages.

![image](https://user-images.githubusercontent.com/3739227/30123337-a0acf870-92ff-11e7-9bc3-8e7d65330f22.png)

**Comment by junezhang** [comment]
The PR has been merged, so close it.
