### ISSUE TITLE
Design:  Improve Applications page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#655]
Rename Applications to Deployments.

Improve the page layout and visual design as an incremental improvement to the page from where it is today.  Also consider highlighting resource usage for each deployment.
https://github.com/openshiftio/openshift.io/issues/773#issuecomment-327810957

**Comment by joshuawilson** [comment]
@mceledonia why was this closed? If done on purpose please add a note as to why it was closed.

**Comment by catrobson** [comment]
@joshuawilson sorry, this somehow got lost in the mix.  The work for the designs is complete, and we opened a new story for stakeholder review to handle any further changes being identified.

Completed designs:
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens

**Comment by catrobson** [comment]
Stakeholder review story:  https://github.com/fabric8-ui/fabric8-ux/issues/701
