### ISSUE TITLE
Dev: Labels/Tags

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#656]
- Take design from #652 
- Implement as part of NGX widgets
- Review with @bdellasc

**Comment by mindreeper2420** [comment]
@bdellasc are these just used in the User Settings screens? If so, should those screens come before the implementation of these label/tag designs?

**Comment by bdellasc** [comment]
I actually don't think they appear anywhere in the current user settings screens. At least I have't heard any mention of them needing to be in there.

They will appear in some form in the Planner (they have it in the list itself, and will probably be in the detail view too. In fact, that's what prompted looking at alternative visuals to what was designed by Sunil.

CC'ing @catrobson

**Comment by catrobson** [comment]
Closing until we take on a larger effort around tagging.
