### ISSUE TITLE
Dev: Change Card empty state to be top-aligned with padding

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#660]
Right now the cards all show text at different height placements because they are center aligned on the Y-axis.  Since we have many cards with many empty states, this can be visually distracting for users.  Work with @bdellasc to determine the correct padding, and change the empty state of these cards to use that padding with top alignment.

**Comment by mindreeper2420** [comment]
This is all set - all of the Dashboard cards have the correct alignment, centered and at the top of each card.

<img width="1867" alt="screen shot 2017-10-28 at 8 41 48 pm" src="https://user-images.githubusercontent.com/4032718/32139746-b50b1bf4-bc20-11e7-99df-836ade1956e3.png">

<img width="1248" alt="screen shot 2017-10-28 at 8 42 08 pm" src="https://user-images.githubusercontent.com/4032718/32139749-ba092c9a-bc20-11e7-8038-e95179a7457a.png">
