### ISSUE TITLE
Dev: Remove Padding Overrides from Cards

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#661]
Remove the padding overrides from the cards, returning them back to the default PatternFly style.

**Comment by mindreeper2420** [comment]
@catrobson @bdellasc here is the layout of the empty states in cards, with the auto-vertical alignment turned off. This assures that all items are top aligned, but they will never be vertically centered, due to the fixed height of the cards (fixed height is needed for the lists we drop in there).

<img width="1709" alt="screen shot 2017-09-15 at 7 53 33 am" src="https://user-images.githubusercontent.com/4032718/30481141-191c81c6-99eb-11e7-816b-e646fbfe908a.png">

**Comment by catrobson** [comment]
@mindreeper2420 this is better than the center alignment for these situations.  Looks good.
