### ISSUE TITLE
Design:  Inline field editing

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#663]
Create a common design for all inline field editing across OSIO, that we can contribute back to PatternFly.

Verification Criteria:
* Designs captured in PatternFly-style in a document for design overview and design.md file for what inline field editing should behave like
* Designs shown in context of OSIO for planner and user profile pages to make sure we understand how they look and act in context of the product
* Add link to design information into fabric8-wiki, Patterns area

Use cases:
* The user is shown a page that is in text format for easy reading and consumption, but should be able to easily edit individual fields on the page and save their changes for those individual edits independently.
* The user is working in a living working page that requires saves to be changed as the user works on different areas of the page as the user will not work through the page top-to-bottom as a normal form page might be.

Scope:
* Basic text field -> Basic text entry input (http://www.patternfly.org/pattern-library/forms-and-controls/data-input/#/text-entry)
* Basic text field -> OSIO Dropdown input (https://github.com/fabric8-ui/fabric8-ux/issues/516)
* List of selections -> OSIO Dropdown input (https://github.com/fabric8-ui/fabric8-ux/issues/516)
* Link -> Basic text entry input (http://www.patternfly.org/pattern-library/forms-and-controls/data-input/#/text-entry) (this can be seen in the user profile)
* Basic long text field -> Markdown enabled editable field (Separate story to create this pattern)
* Ensuring to collaborate with development to consider accessibility concerns with this pattern

Prior work to reference:
https://github.com/fabric8-ui/fabric8-planner/issues/990
https://github.com/openshiftio/openshift.io/issues/785

**Comment by junezhang** [comment]
I remembered @zhutaoredhat posted a blog about "inline edit" on PatternFly.
https://blog.patternfly.org/inline-edit-on-forms-conceptual-design/ 
He will work on this issue for the inline edit in OSIO.

**Comment by zhutaoredhat** [comment]
@catrobson Here is a mockup of inline edit created by jason and me. https://github.com/patternfly/patternfly/pull/671

**Comment by catrobson** [comment]
Thanks for posting @zhutaoredhat - I still need to review, but talked to Matt about continuing to move this forward for the pattern.

**Comment by zhutaoredhat** [comment]
@catrobson Ok, thanks~

**Comment by catrobson** [comment]
Pull request submitted in PatternFly here:  https://github.com/patternfly/patternfly-design/pull/452 . Closing this issue.
