### ISSUE TITLE
Dev: Add 'Saved Filters' capability to Filter pattern in patternfly-ng

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#664]
We need to add saved filter capabilities, as specified by the design linked below, to patternfly-ng repo.  We'll be contributing the design as a second step separate from this story.

Design:
https://redhat.invisionapp.com/share/DUDF5ZA7J (Option 1)

Verification criteria:
* Capability added to filter pattern, PR reviewed and accepted by ng reviewers & Sunil, Samir

**Comment by dlabrecq** [comment]
I'm confused by the search bar in the filter menu. We recently added type ahead functionality, which basically does the same thing. Can we not use type ahead to prune the available custom filters?

**Comment by catrobson** [comment]
+1 the search bar should not be there - type-ahead handles this.  This was agreed upon but the wireframes were not updated to reflect that discussion it looks like.

**Comment by dlabrecq** [comment]
There is also an issue with table views. That is, where the "save filter" control is located, we also display the number of selections. For example:

![screen shot 2017-10-11 at 9 58 01 am](https://user-images.githubusercontent.com/17481322/31444655-d3d5c5ac-ae6a-11e7-8795-ed3bffbbb9ae.png)

**Comment by catrobson** [comment]
Just capturing here that we agreed we could put the save filter alongside "clear all filters"

**Comment by dlabrecq** [comment]
Quick question. Should the "My Filters" option be visible when the user has not saved any filters? Or, after the user has removed all of their saved filters?

![screen shot 2017-10-13 at 10 44 21 am](https://user-images.githubusercontent.com/17481322/31551831-c1308a82-b003-11e7-9790-03c0ef864564.png)

**Comment by muruGanesan** [comment]
IMO: we can 'gray out' (disabled state) when there is no data.  - THIS CAN BE A COMMON BEHAVIOR for SUCH KIND OF CONTROLS.
Option-1
![option-1](https://user-images.githubusercontent.com/26006817/31553846-6861cadc-b059-11e7-9bdc-c30bf0e4d7d1.jpg)

Option-2
![option-2](https://user-images.githubusercontent.com/26006817/31553904-90d47578-b059-11e7-8ee7-d54278bc2a88.jpg)

**Comment by muruGanesan** [comment]
@catrobson , sdash@redhat.com
Please review my comments and provide your opinion

**Comment by dlabrecq** [comment]
I disabled the filter field as shown in option 1. The PR and demo can be found here:
https://github.com/patternfly/patternfly-ng/pull/155

**Comment by dlabrecq** [comment]
Closing for the end of sprint 139-1. Please refer to the PR above.
