### ISSUE TITLE
WIREFRAME: First pass of the Comparison Page

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#665]
Add a feature where the user can compare two or more experiments against one another and compare and contrast them. This could include both in progress and completed experiments.

**Comment by lwrigh** [comment]
![compare 3 copy 3](https://user-images.githubusercontent.com/20227374/30665444-ff6877ac-9e1e-11e7-8440-dd34985e881d.png)

**Comment by lwrigh** [comment]
https://redhat.invisionapp.com/share/UVDLVHFMX

**Comment by catrobson** [comment]
@lwrigh looks like some good options.  Let's get the "Compare another experiment" control folded into the last design where you have two different metrics for the two experiments on the screen, and get that screen folded into the larger clickable prototype as a next step.

Control on this screen: https://redhat.invisionapp.com/share/UVDLVHFMX#/screens/254864479/comments

Would like to see screen for brought into the end to end prototype: https://redhat.invisionapp.com/share/UVDLVHFMX#/screens/254864476
