### ISSUE TITLE
DESIGN: Selecting more than 1 instrument for an experiment 

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#666]
Add the ability to add more than 1 type of instrumentation to an experiment

**Comment by lwrigh** [comment]
![select instrument](https://user-images.githubusercontent.com/20227374/30561143-0cbc67bc-9c88-11e7-9010-236269f4c088.png)
![select instrument 1 1](https://user-images.githubusercontent.com/20227374/30561144-0cdad21a-9c88-11e7-8abf-a51aa6c0955a.png)
![select instrument 1 2](https://user-images.githubusercontent.com/20227374/30561145-0cee7428-9c88-11e7-8824-43ca9aa80788.png)
![select instrument 2 1](https://user-images.githubusercontent.com/20227374/30561146-0d01ec7e-9c88-11e7-83a4-ebc8047b85c5.png)
![select instrument 2 2](https://user-images.githubusercontent.com/20227374/30561147-0d125c62-9c88-11e7-93d7-c22a0f25d27e.png)
![select instrument 3 1](https://user-images.githubusercontent.com/20227374/30561148-0d2a6898-9c88-11e7-8d90-1507667e8042.png)
![select instrument 3 2](https://user-images.githubusercontent.com/20227374/30561150-0d3bcfac-9c88-11e7-962b-107d4f8bbc65.png)

@catrobson I was looking at the work the Beijing team has been doing on the multi select for OSIO and thought it might be a good use case for selecting multiple different types of instruments. What do you think?

**Comment by lwrigh** [comment]
https://redhat.invisionapp.com/share/48DK8PVB9 Select instrument 1.1-1.4 are based off of the multi select and filter list on patternfly

**Comment by catrobson** [comment]
@lwrigh looks good.  Can we get this folded back into the full clickthrough prototype as a new story?

**Comment by lwrigh** [comment]
@catrobson Yup, this can be included in the full prototype. I'll link this issue to the new story.
