### ISSUE TITLE
Review space list view with Dev and PM stakeholders

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#681]
Set up a review with Dev and PM stakeholders to walk through the current wireframes and visual design thinking for viewing all spaces.   We need alignment on this so that we can finalize designs and start to move into development within the next week.

Record the session and capture the feedback in InVision for consumption by the Beijing team.

Stakeholders:
Dev - (required) Joshua, Aslak (optional) Corinne, Len, Xavier, Max
PM - (list all as required) Brad, Todd, Stevan

**Comment by bdellasc** [comment]
Meeting with @catrobson and @joshuawilson today to review the current state of the design before we schedule the wider conversation.

**Comment by bdellasc** [comment]
Scheduled, the rescheduled the meeting to 9/28/17 because of a conflict with an OSIO workshop happening at the same time.
