### ISSUE TITLE
Design:  Username or Org name in space selection

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#682]
Consider how we would show username or organization name in the space selection.  This will affect the top left contextual menu and any place that we refer to a space.

Verification Criteria:
* Come up with design options of how we would notate org/username > space anytime we show a space.  Post to InVision.
* Catalog all areas of OSIO that would be affected by this change and consider if there are any design variants needed given the usage across the system.  Post catalog of areas into google doc against this issue.

**Comment by bdellasc** [comment]
InVision mockups [here](https://redhat.invisionapp.com/share/ZBDRCMI89)
