### ISSUE TITLE
Discuss application wizard

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#685]
A meeting is forthcoming.

**Comment by catrobson** [comment]
Attended meeting and the following action items were noted:

* HTML/CSS review of wizard before merge.  Sarah Rambacher is working on this.
* Consider how the mission from launch could work into this wizard.  I will create separate work item for this.
* Provide guidance for final summary page using information available here: https://github.com/fabric8io/fabric8-test/blob/master/EE_API_automation/pyresttest/import_wizard/step_4_2_output.json#L11-L32.  Will Create separate issue for this.
* Review after PR is merged and submit bugs with any design improvements beyond this
