### ISSUE TITLE
Visual Design:  Not Authorized error page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#686]
https://github.com/openshiftio/openshift.io/issues/1023#issuecomment-332018296

**Comment by catrobson** [comment]
Use Case

The user hasn't been granted access to OSIO yet (they are on wait list) but does have a RHD login.  They log into OSIO and we need to tell them that they have not been granted access to the OSIO platform.  

Options for the user from this page: 

- They should still be able to navigate to public spaces to view activity on those public spaces.  (Question for dev - would they have to log out for this to work?)
- They could go view their OSIO wait list status (page needs to be evolved from current)
- They could get started with OSO today to build and deploy applications

**Comment by bdellasc** [comment]
The one mockup I did in the darker style was in the source file here. It's in the bottom row of artboards:
https://drive.google.com/drive/folders/0BwL_r77doqY_RkNzbFdvUUVqNkk?usp=sharing

**Comment by mceledonia** [comment]
Latest design:

https://redhat.invisionapp.com/share/P7DZZ8QHK

**Comment by catrobson** [comment]
Issue raised by dev:

This is actually a bit more complicated. We do not know if unapproved user is in a waiting list or not. So there are two scenarios:

User has never signed up and trying to login.
User has signed up but still in a waiting list and trying to login.
@luciddreamz is there any REST API available for us to check if user signed up in the registration app?

**Comment by catrobson** [comment]
@joshuawilson - can you comment on how you think we should proceed with this?  It sounds like we just don't have the information to do what was originally proposed around showing a useful error if a non-registered user tries to log in.

I could see two solutions:
- Have this page be much more generic - just saying they don't have access to OpenShift.io for some reason.
- Consider other ways of determining whether the user is on the waitlist.  Not clear if there are any other options here.

**Comment by joshuawilson** [comment]
@catrobson there is no API at all to get info out of the wait-list. We will have to settle with telling them they can't login.

As to your earlier question, if a use is logged into RHD that does not effect their ability to view OSIO. They just don't have an account of their own.

**Comment by mceledonia** [comment]
Updated and posted a couple versions with Jake's suggestion [here](https://redhat.invisionapp.com/share/P7DZZ8QHK)

**Comment by joshuawilson** [comment]
@mceledonia that screen says "you are not authorized to access OpenShift.IO" but that is not exactly correct. It would be more accurate to say "you are not authorized to access this section of OpenShift.IO"

That is just a suggestion, the actual wording should come from @catrobson and Todd

**Comment by catrobson** [comment]
@joshuawilson Its not about sections in this case, in this case the user cannot access the OpenShift.io application at all - they haven't been granted access by us.

**Comment by joshuawilson** [comment]
But everyone should be able to access OSIO. They just can't change things. This is a permissions issue not an access issue. 

For example, if you open OSIO in incognito, do NOT login, just go to https://openshift.io/openshiftio/openshiftio/ you can see things and open up pages. Just can't edit anything.

**Comment by catrobson** [comment]
Right, there is a way to access information when you are not logged in, but as soon as you log in and try to authenticate yourself is where you're hitting this page.  We do say on the page that you can access any view-only openshift.io URLs shared with you.

**Comment by joshuawilson** [comment]
ok, thanks
