### ISSUE TITLE
Fabric8 Design Template

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#695]
Update our sketch file to include the latest patterns that are used in OpenShift.io, as well as providing a standard cover page.

Acceptance criteria:
* Sketch file created with:
** PatternFly and OpenShift.io symbols for reuse **OR** Sketch file with instruction on how to import PatternFly and OpenShift.io libraries
** Standard cover page, Table of Contents
** Standard layout for capturing use cases (or linking to use case documents)
** Standard layout for capturing user flows
* Reviewed with OSIO Designers (US and India)
* Posted on Fabric8-ux wiki and other locations as needed for access

**Comment by lwrigh** [comment]
Google doc with content and criteria ideas for the template: https://docs.google.com/a/redhat.com/document/d/1gSxigDEbRBKGfscLY7Ir50yAZ7Y9tEo7zlSA54A2ieY/edit?usp=sharing

In progress Sketch template Invision document: https://redhat.invisionapp.com/share/P5DY1GM27

@catrobson
