### ISSUE TITLE
Wireframe:  Wizard summary screen & information

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#696]
Provide updated design guidance for the wizard summary screen.  It is designed to handle both quickstart and import flows, and in the import flow situation it might create multiple results.  The information returned is in this json file that we can use:  
https://github.com/fabric8io/fabric8-test/blob/master/EE_API_automation/pyresttest/import_wizard/step_4_2_output.json#L11-L32

Acceptance criteria:
* Consider what the final summary page of the wizard should show users and update wizard designs with this information
* Consider what information we should allow the user to locate after wizard use, and consider where the in the UI this information should live.  Depending on size of effort, either create wireframes to capture this or create a new issue to capture this work.

**Comment by catrobson** [comment]
@corinnekrych - can you help identify where we can find the JSON output of the wizard - the above link is now a 404 error

**Comment by lwrigh** [comment]
https://github.com/fabric8io/fabric8-test/blob/master/EE_API_automation/pyresttest/forge_wizard/import_wizard/step_4_2_output.json

**Comment by lwrigh** [comment]
https://redhat.invisionapp.com/share/UME00N9CD#/258851443_Wizard_Summary_Screen

**Comment by lwrigh** [comment]
https://redhat.invisionapp.com/share/UME00N9CD Most recently updated link to the Invision document
