### ISSUE TITLE
Design:  Access to MatterMost chat from OSIO

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#705]
To help users talk to us for more self-service support as they start using OSIO, we want to be able to point them to our MatterMost channel.  Design where we can guide the user towards our MatterMost channel in product, potentially with any instructions needed for them to get it set up successfully.

VC's
* Workflow captured
* Wireframes created
* Post to Wiki
* Review with Catherine, Todd, Joshua

**Comment by lwrigh** [comment]
I was able to get a first pass done today and here's the Invision project with it: https://redhat.invisionapp.com/share/QYE48G346 I have also attached a link to the Sketch file for download: https://drive.google.com/a/redhat.com/file/d/0ByyY35rYs5Mtc1A2MHZXaDdrb2c/view?usp=sharing

@catrobson @mindreeper2420 @bdellasc

**Comment by bdellasc** [comment]
I feel like the flow where the user clicks on the "Chat in Mattermost" menu option is the most straight-forward and gets the user where they need to be in the most direct way. I added this comment to the InVision as well.

**Comment by mindreeper2420** [comment]
PR here: https://github.com/fabric8-ui/fabric8-ui/pull/2199
