### ISSUE TITLE
Visual Design:  Repositories and Workspaces

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#707]
Work through the visual design of the repositories and workspaces pages to determine how we handle backgrounds and layouts of these pages.  Sketch file is here: https://drive.google.com/open?id=0B4cAquu_bfjpcWRtejdnUDJTa00. Coordinate with Catherine about when to start editing the file.

**Comment by catrobson** [comment]
@mceledonia can you post your visual design file here for reference?

**Comment by mceledonia** [comment]
https://redhat.invisionapp.com/d/#/projects/prototypes/12588285
