### ISSUE TITLE
Dev: Update User Profile Section to Match Visuals (advanced)

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#715]
Update the User Profile section to match the visual designs from https://github.com/fabric8-ui/fabric8-ux/issues/621.

Any items that cannot be connected need to be noted and shared.

- [x] User Profile page
- [x] Experimental Features page
- [x] Notifications page
- [x] Resources page
- [x] Consume PatternFly-ng vertical nav

**Comment by mindreeper2420** [comment]
Pages that need to be wired to OpenShift.io:
- User Profile
  * Active Experimental Features
  * Activity
- Experimental Features
- Notifications

Pages that need to be wired to OpenShift Console:
- Resources

**Comment by mindreeper2420** [comment]
@catrobson @dlabrecq @dgutride I've wired up as much as I can to the designs and areas. The biggest pieces are (of course) the ones that haven't existed previously (turning on individual experimental features, notifications) and referencing information from OpenShift (resources). I'm not sure the best way to go about this, but I believe that I've taken this as far as I can.

I've configured that masthead to be static, in order to fit inline with the PatternFly vertical nav. It turns out that this matches OpenShift as well, so there will be continuity between the two environments.

The branch can be found here: https://github.com/mindreeper2420/fabric8-ui/tree/user-profile-update

**Comment by mindreeper2420** [comment]
Production version of the User Profile page:
![screen shot 2017-10-24 at 4 12 57 pm](https://user-images.githubusercontent.com/4032718/31965735-431cc378-b8d6-11e7-8dbc-0b35ad44bacc.png)

Development Version:
![screen shot 2017-10-23 at 11 14 37 am](https://user-images.githubusercontent.com/4032718/31965748-52ea0716-b8d6-11e7-9d12-678d9936e491.png)

**Comment by alexeykazakov** [comment]
We need to add "Remove" and "Update" (or something else that will re-connect accounts) buttons/links for My Connected Accounts. If the connection is missing then "Connect"/"Link" button.

**Comment by dlabrecq** [comment]
We had that feature in the profile page before, but removed it. Unless you're already on updating your profile, it wasn't very useful. (It only worked when I quickly removed my tokens from KC while still on that page.) The login client will log you out, and direct the user back to getting started, when it detects tokens are no longer available. And detecting the tokens is our only way to determine if those controls should be shown on the profile page.

**Comment by alexeykazakov** [comment]
We will need to refactor our getting started page later. Because eventually we should ask users to link accounts on demand. Not on login. But even for now we need this connection settings back to profile page.
We now can update connections/re-connect accounts (will update tokens). And we now can remove connections (even if it currently logs out user. User still has to be able to remove connects/delete tokens).

**Comment by dlabrecq** [comment]
Didn't realize there was a remove feature available -- makes more sense now. I was speaking only about the update feature we once had in place.

**Comment by alexeykazakov** [comment]
@dlabrecq well, it's almost available ;) Should be done this week - https://github.com/fabric8-services/fabric8-auth/pull/152 (currently under review)
And the update feature is available just for the last couple of weeks. So, I agree that it didn't make sense to keep this in the profile page. But now it does.

**Comment by mindreeper2420** [comment]
Implement incremental view of User Profile, including visual design updates and flows.

- [ ] Create a new branch w/slimmed-down view
- [ ] Hide Activity Feed
- [ ] Hide Individual Experimental Features

**Comment by mindreeper2420** [comment]
https://github.com/mindreeper2420/fabric8-ui/tree/user-profile-slim

**Comment by mindreeper2420** [comment]
Slimmed version, with layout and visual updates:
![screen shot 2017-10-30 at 11 04 50 am](https://user-images.githubusercontent.com/4032718/32193384-78421bdc-bd8d-11e7-86cd-47168aa8b8de.png)

**Comment by alexeykazakov** [comment]
@mindreeper2420 what about (Re-)Connect/Update/Delete actions for GitHub/OSO accounts?

**Comment by mindreeper2420** [comment]
@alexeykazakov that will come in a later update. The plan right now is to do this in stages, rather than hold everything back until all of the pieces are completed.

The first step is a visual update, with the Connected Account information (since it is only visible on the Getting Started page today).
The second, etc. steps will be to add functionality and break out pieces from the 'Update Profile' section into their own areas, as those will be expanded as well.

**Comment by mindreeper2420** [comment]
Requires https://github.com/fabric8-ui/fabric8-ux/issues/727

**Comment by mindreeper2420** [comment]
This will be implemented once the IA has been updated.

**Comment by mindreeper2420** [comment]
Closing as it is now out of date and a newer version is being implemented.
