### ISSUE TITLE
WIREFRAME:  Connect to git

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#721]
Throughout the UI, we'll have new blocking points where the user will need to provide git information.  In the short term, they will only be able to connect to github.  In the longer term, the user could connect to multiple git providers.  

Capture the flows, checkpoints, and wireframes for user git connecting.

Acceptance criteria:
- [x] User flows captured for various checkpoints where git account would be requested
- [x] User flows shared with UXD, devtools-saas
- [x] Wireframes for git account connection short term captured (github only)
- [ ] Wireframes for git account connect long term captured (multiple git providers - use placeholders)
- [x] Flows and Wireframes posted to fabric8 wiki
- [x] Wireframes shared with UXD, devtools-saas

**Comment by mindreeper2420** [comment]
Wireframes and Flows for connecting GitHub: https://redhat.invisionapp.com/share/A8EC5AXWH

**Comment by catrobson** [comment]
Looks good!

**Comment by catrobson** [comment]
Note that connecting to github during the create project flow is being handled by the Launch & OSIO merge stories Laura is handling.

**Comment by mindreeper2420** [comment]
Related to https://github.com/fabric8-ui/fabric8-ux/issues/697

**Comment by mindreeper2420** [comment]
Shown to Alexei & Shane as part of their connecting/disconnecting work. Still need to share with the devtools-sass list and post to the fabric8 wiki once completed.

**Comment by mindreeper2420** [comment]
Updated wireframes/flows based on conversations with Shane and Alexey. Email sent out to the distribution list for feedback, with InVision links included.

**Comment by mindreeper2420** [comment]
Currently under review in InVision by devtools-sass members. Wireframes and flows have been updated accordingly.

**Comment by catrobson** [comment]
Moved multiple git providers into new story.  Closing this story as completed.
