### ISSUE TITLE
Requirements Gathering:  UI Feature Flags

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#724]
Requirements have been started here:
https://docs.google.com/document/d/1zzN1OKCAf2seOyInnfJwD_fxdOQupJdWIDUaB7-A-iE/edit?ts=59f9dc66

Review these requirements, and come up with a list of questions, assumptions, use cases, and possibly user flows that we can talk about more with stakeholders.

**Comment by mindreeper2420** [comment]
@mceledonia not sure if this is a helpful starting point at all, but the Experimental Features PatternFly documentation is here: http://www.patternfly.org/pattern-library/communication/experimental-features/

**Comment by catrobson** [comment]
Set up meeting with UXD to discuss and come up to speed as a team on this feature.

**Comment by mceledonia** [comment]
First draft of options toggling is up:
https://redhat.invisionapp.com/share/4EEE2JAQ7

**Comment by catrobson** [comment]
Michael sent out wireframes around this in December:
https://redhat.invisionapp.com/share/4EEE2JAQ7

A limited set will be implemented in this Train.  Closing issue until further UXD work is identified.
