### ISSUE TITLE
Visual Review: Email Templates

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#725]
@bdellasc @mceledonia Can you review these email templates from a visual design perspective? With the changes that have been to OpenShift.io, I'd like to get a sense for what can be done to have these match the overall aesthetic that you are working towards.

![changestatus](https://user-images.githubusercontent.com/4032718/32302778-df824af2-bf3a-11e7-8729-de5f94653489.png)
![commentitem](https://user-images.githubusercontent.com/4032718/32302779-df8c9778-bf3a-11e7-9054-597c8940fdc6.png)
![createitem](https://user-images.githubusercontent.com/4032718/32302780-df9e950e-bf3a-11e7-87d4-0ce58efa3161.png)
![updateitem](https://user-images.githubusercontent.com/4032718/32302781-dfae87a2-bf3a-11e7-8312-5f1a4168b834.png)

**Comment by bdellasc** [comment]
I posted a mockup [here](https://redhat.invisionapp.com/share/9DEC9TARM). It's not all that different from the mockups included in this story, but it opens up the spacing and suggests some slight format changes.

**Comment by mindreeper2420** [comment]
I'm closing this, as the Dev work is completed, and the PR has been submitted. Thanks!
