### ISSUE TITLE
Wireframe:  Connect and disconnect accounts

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#728]
Allow the user to connect and disconnect OpenShift and GitHub accounts.

**Comment by mindreeper2420** [comment]
related to https://github.com/fabric8-ui/fabric8-ux/issues/721

**Comment by mindreeper2420** [comment]
Wireframes and Flows for connecting GitHub: https://redhat.invisionapp.com/share/A8EC5AXWH

**Comment by mindreeper2420** [comment]
Wireframes and Flows for connecting OpenShift Console: https://redhat.invisionapp.com/share/BWEGW3R38

**Comment by catrobson** [comment]
Updates and wireframes look good Adam.  Generally would love to clean up the OpenShift flow and I know you are following up some more on that.

**Comment by mindreeper2420** [comment]
This work is currently a PR in fabric8-ui (https://github.com/fabric8-ui/fabric8-ui/pull/2244). As such, I'll close this and continue to work with Shane in that PR.
