### ISSUE TITLE
Design:  OpenShift.io/Status page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#729]
Design a page that lives outside of OpenShift.io that provides a full status of all parts of the system, as well as outage reports and information.

Talk to Todd about requirements.  Look at other examples out there such as our own Customer Portal, Twitter, Netflix, etc.

Acceptance Criteria:
* Requirements and competitive analysis gathered and captured
* Wireframes of page created and shared with devtools-saas
* Wireframes posted to fabric8 wiki

**Comment by lwrigh** [comment]
@catrobson Here's the document I've started to put together that does a competitive analysis of different status pages https://docs.google.com/a/redhat.com/document/d/1BUcoo2FerdixLWZspjh5Z-VT2MLHFU-BGmQ_FwucEag/edit?usp=sharing

**Comment by catrobson** [comment]
Nice!  I like the variety of options this shows but also the commonality.  Let's make sure we have captured the set of use cases and requirements we're moving forward with as assumptions for design purposes as we start designing.

**Comment by lwrigh** [comment]
@catrobson I've started to consolidate some of the possible use cases for the status page in this document

https://docs.google.com/a/redhat.com/document/d/1yMbmJN7jBFQ9gPF9F5TyCgzaposoArwKLD6XOb5tLjc/edit?usp=sharing

Does anything seem to be missing from it?

**Comment by lwrigh** [comment]
@catrobson Here's a first pass at the wireframes 
https://redhat.invisionapp.com/share/GFEJ8RRY8

**Comment by lwrigh** [comment]
I have sent out an email to the devtools-saas mailing list to see if there are any additional comments or pieces of feedback that should be included in the wireframes. I can update the wireframes accordingly.

**Comment by maxandersen** [comment]
Proposals looks nice. Have there been an investigation into just using something like statuspage.io which would (as I understand it) limit our ability to affect the UX but at least ensure we had a completely separate system that we could just use now + it would not go down if openshift runs down ?

**Comment by lwrigh** [comment]
Most recent wireframes: https://redhat.invisionapp.com/share/GFEJ8RRY8
