### ISSUE TITLE
Che icons

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#733]
https://docs.google.com/a/redhat.com/presentation/d/127E56WZ0IUaBxRzeXXNXj69Z6KhfKYAyV0RqfIVEIG0/edit?usp=sharing

Icons needed:
- Active breakpoint
- Active breakpoint - conditional
- Disabled breakpoint
- Disabled breakpoint - conditional
- Inactive breakpoint
- Inactive breakpoint - conditional
- Resume
- Step into
- Step over
- Step out
- End debug session
- Remove all breakpoints
- Change value
- Evaluate Expression
- Go to line
- Suspend
- Add expression
- Remove expression
- Expression icon
- Unavailable expression

Verification Criteria:
- Icons created and shared with UXD, Stevan Lemur (slemeur@redhat.com), Anatolii Bazko (abazko@redhat.com)
- Icons posted into github fabric8 wiki

**Comment by catrobson** [comment]
For those icons, we are using SVG format. 
In term of size, they should look great in 16x16.

**Comment by bdellasc** [comment]
Chatted today with Stévan Le Meur RE: context and technical questions for the Che icons. Posted the [chat transcript here](https://docs.google.com/a/redhat.com/document/d/1t-UMgMGgsu6apBfVmRsPgWKqg-eV785agEGuiDLU20I/edit?usp=sharing):

**Comment by bdellasc** [comment]
Posted icons to the Google drive and e-mailed Stevan and Anatolii the link. If they need to be posted elsewhere, will follow up with them.
