### ISSUE TITLE
Dev: Space List - basic implementation

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#734]
Verification Conditions:

- Implement the parts of the list that are currently supported with APIs we have available?:
   - Space Name
   - Space Owner
   - Space Description
   - Kebab Menu
   - Pinning rows
- Match the visuals in [InVision](https://redhat.invisionapp.com/share/DQDSL22JA)
- Review with visual design

**Comment by bdellasc** [comment]
Met with @dlabrecq RE: implementation. He thinks "pinning" will be possible to implement in the short term and will investigate adding that functionality to the list component.

As requested, here are PatternFly colors, etc for the pinned area in the mockup:

Pinned BG color: pf-black-150
Inner right shadow for pinned BG: 
.shadow {
   -moz-box-shadow:    -3px 1px 4px 0 #ededed;
   -webkit-box-shadow: -3px 1px 4px 0 #ededed;
   -box-shadow: inset -3px 1px 4px 0 #ededed;
Pin icon: "fa-thumb-tack" pf-black-600
Private icon: "pficon-locked" pf-blue-400

**Comment by dlabrecq** [comment]
Before we can use the new pinning feature from the list component, we have to upgrade OSIO to patternfly-ng v1.x. This introduces a breaking change to the list headings used in the OSIO codebases page. As a first step, we need to bump the patternfly-ng version number for OSIO and update the codebases page.
