### ISSUE TITLE
Wireframe: New project as progressively building whole screen

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#740]
As another alternative to the modal with wizard wireframes, I'd like to see us try a progressively building page to select and create a new project.

Verification Criteria:
* Alternative wireframe sets created
* Shared with UXD
* Feedback collected and InVision updated with only the screens that we plan to show to stakeholders
* Screens shared with stakeholders

**Comment by lwrigh** [comment]
@catrobson Here is a first pass of the new project flow as a progressively building page: https://redhat.invisionapp.com/share/ZVEGQJKE8

**Comment by lwrigh** [comment]
@catrobson Here are some updated wireframes that reflect the feedback you left on the last one and some of the comments from the stakeholder meeting today: 
https://redhat.invisionapp.com/share/ZVEGQJKE8

**Comment by lwrigh** [comment]
@catrobson Here are the most up to date wireframes: 

https://redhat.invisionapp.com/share/3NEIZMAV4

**Comment by lwrigh** [comment]
@catrobson Here are the updated wireframes: 

https://redhat.invisionapp.com/share/3NEIZMAV4

**Comment by lwrigh** [comment]
Added the final pages for selecting either OSIO or OSO 

https://redhat.invisionapp.com/share/3NEIZMAV4

**Comment by lwrigh** [comment]
Made edits to the wireframes, here's the Invision link to it: 

https://redhat.invisionapp.com/share/95ERABN7V

**Comment by catrobson** [comment]
Presented to team and general direction bought off on.  Closing this story.
