### ISSUE TITLE
RESEARCH: Recruiting for merged wizard interviews

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#742]
- Ping Stevan for suggested contacts
- HIt up dev mailing lists
- Schedule

**Comment by catrobson** [comment]
Didn't get a chance to talk to you this morning.  I think we could also see if there are existing customers and users on our installed products that we could reach out to around this.  Maybe reach out to Bob Davis as well to see what possibilities we have there.  I also think it would be nice to start thinking about a DXP customer base for 'developers' in general - and Bob might be able to help us identify existing customers using on-desktop solutions today.

**Comment by Essjaysee** [comment]
Thanks for the lead.  I reached out to Bob, but he's PTO for Thanksgiving.  Will catch up with him next week!

**Comment by Essjaysee** [comment]
Bob's on the case.  Dan pinged the channels on Mattermost and got 4 who are willing, I have 1 scheduled, and will be pinging the developer mailing list this afternoon.

**Comment by Essjaysee** [comment]
Closing because @lwrigh and I conducted 10 internal interviews that I recruited via the mailing lists.  Will open a new story to track recruiting for external interviews.
