### ISSUE TITLE
Errors Contained within Cards

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#752]
Currently, we have a set of full screen error pages for various returns (401, 500, etc). As a single given card on a dashboard can have an error, yet the rest of the page can be functioning properly, we need a method for showing errors inside of cards. 

Ideally, these would mimic the ‘blank state’ designs that currently exist, but with additional information and actionable items.

**Comment by adisakala** [comment]
@muruGanesan request you to look at this issue.

**Comment by muruGanesan** [comment]
@adisakala I spoke to Adam and I knew the issue, today it will be fixed.

**Comment by muruGanesan** [comment]
Please review the error/warning page design
https://redhat.invisionapp.com/share/KGE3V2B79#/265822086_OSIO_Analytics_V07_Error-001
