### ISSUE TITLE
Wireframe: Search Results

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#761]
When the user uses our search, they will be brought to a search results page.  The search results page should be able to show a variety of result types (work items, code snippets from source code, deployments, etc).  The user should be able to filter the set of results dynamically, supporting the following types of filtering:

Filter by type
Filter by context (all of OSIO, only spaces I am a owner/collaborator on, specific spaces)
Filter by person (might also only show certain result types)
Filter by keyword

Acceptance Criteria:
[X] Wireframes created and shared with UXD team, posted to this issue
[X] Wireframes posted to fabric8 wiki
[X] Wireframes sent to devtools-saas

**Comment by lwrigh** [comment]
Talk to Tiffany about RHD search work

**Comment by lwrigh** [comment]
@catrobson First pass at search results page

Invision link: https://redhat.invisionapp.com/share/3HF99DKQD

**Comment by lwrigh** [comment]
@catrobson Added a context selector to the search bar in the top nav, refined the filters, and edited the layout of the search results. 

https://redhat.invisionapp.com/share/3HF99DKQD

**Comment by lwrigh** [comment]
@catrobson  I was able to update the wireframes based off of feedback from design review. 

Invision link: https://redhat.invisionapp.com/share/WQFA7QEUS

**Comment by lwrigh** [comment]
I was able to send out the wireframes to the devtool-saas mailing list for feedback so I can adjust the wireframes depending on the feedback that is received from the mail list.
