### ISSUE TITLE
Wireframe:  Add reset password link to user settings

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#763]
Add a link to reset the user's password into the user settings somewhere

**Comment by mindreeper2420** [comment]
Would this be in the existing User Profile section, or as part of the updated design?

**Comment by catrobson** [comment]
Updated design probably in user settings

**Comment by catrobson** [comment]
Posted link to InVision here: https://redhat.invisionapp.com/share/3KF6YHUYQ
Submitted PR to wiki to include link (https://github.com/fabric8-ui/fabric8-ux/pull/800)
Added source file to google here: https://drive.google.com/open?id=0B_zZwzicsCVzX05HUk13LXF5ZkU

**Comment by catrobson** [comment]
Wireframes reviewed by UXD and Dev.  Ready for Dev, Closing.
