### ISSUE TITLE
Wireframe:  Profile & User Dashboard

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#769]
Consider what belongs on the users profile vs. the user dashboard, and update wireframes to reflect this.

Use cases:
- Another user can view a user's profile (profile)
- I can view/edit my profile information that others see (profile)
- I want to see my content that I can quick link off of into the system (user dashboard)

**Comment by mceledonia** [comment]
Sounds like we want to split User Profile and User Settings, whereas now they are combined. Is this split something we want to handle with this cleanup effort or would it be better to handle in a future sprint? Split would mainly consist of creating user settings page/experience which shouldn't be too much work on my end.

**Comment by catrobson** [comment]
Let's do this as part of the cleanup effort.

**Comment by mceledonia** [comment]
Invision Link (pending)
