### ISSUE TITLE
HTML/CSS: Not Authorized page

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#771]

**Comment by mindreeper2420** [comment]
@catrobson is the design for the Not Authorized pages from @mceledonia?

**Comment by catrobson** [comment]
@mindreeper2420 - yes.  Found here:  https://redhat.invisionapp.com/share/BGEPRG73N

**Comment by mindreeper2420** [comment]
<img width="1920" alt="screen shot 2017-12-06 at 3 12 31 pm" src="https://user-images.githubusercontent.com/4032718/33684248-a04a0614-da9b-11e7-9bde-806ef29bdf1f.png">

**Comment by mindreeper2420** [comment]
PR filed.

**Comment by alexeykazakov** [comment]
I can't reopen this issue but the page doesn't seem to work for me - https://github.com/openshiftio/openshift.io/pull/1518#issuecomment-352104705

**Comment by mindreeper2420** [comment]
@alexeykazakov I'm able to get to the page on prod-preview (https://prod-preview.openshift.io/not-authorized.html). It does not appear to be in production yet.

**Comment by alexeykazakov** [comment]
Yeah.. it has not deployed to prod yet. But it does not work for me in preview either. When I click on "Sign up or check for approval status" button nothing happens.

**Comment by mindreeper2420** [comment]
Yes, it is not wired up yet. Just the HTML/CSS. There is no way for a user to get to that page unless they know the exact URL.

**Comment by alexeykazakov** [comment]
To be clear. Auth backend will redirect to this page when this page is available and ready. But the page itself should be fully functional. "Sign up or check for approval status" should open https://manage.openshift.com/openshiftio

**Comment by mindreeper2420** [comment]
@alexeykazakov a new story should be added then to hook up the actions on the page. That wasn't part of this original story :)

**Comment by alexeykazakov** [comment]
OK. Never mind ;) https://github.com/openshiftio/openshift.io/pull/1701
