### ISSUE TITLE
HTML/CSS for table components

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#772]
Pagination, filter, drag and drop

**Comment by mindreeper2420** [comment]
Updated toolbar and filter results background, as well as row hover:
<img width="1610" alt="screen shot 2017-12-05 at 11 42 49 am" src="https://user-images.githubusercontent.com/4032718/33618789-7bd9c57a-d9b1-11e7-94a9-18dc810f9c07.png">

**Comment by mindreeper2420** [comment]
Continuing to work on this - everything that has been implemented in PatternFly-ng has been updated with the new styles. Currently waiting on selected with checkbox and updating drag and drop styles.
