### ISSUE TITLE
JS:  Table component into patternfly-ng

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#773]
Add components for the table component from ngx-datatables into patternfly-ng

**Comment by dlabrecq** [comment]
I have an initial table component with a PatternFly toolbar (sort, filter, etc.), pagination. I recently introduced a directive for drag and drop. All these features still need CSS work.

There are also some issues with wrapping the ngx-datatable with another component. I'll skip the details here, but trying to work out a solution for users being able to provide a custom HTML layout.

**Comment by dlabrecq** [comment]
Completed: https://github.com/patternfly/patternfly-ng/pull/270

**Comment by catrobson** [comment]
PR submitted:  https://github.com/patternfly/patternfly-ng/pull/270
