### ISSUE TITLE
Wireframe:  Import existing project flow into decided new project designs

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#775]
As we decide on direction for the wizard, import existing project also needs to be folded into this design.

**Comment by lwrigh** [comment]
Here's a first pass at adding the ability to import an existing project through the merged wizard: https://redhat.invisionapp.com/share/EGF2SMJQ3

**Comment by lwrigh** [comment]
Here's a second pass at the wireframes. I made refinements based off of comments from @catrobson 
https://redhat.invisionapp.com/share/EGF2SMJQ3
