### ISSUE TITLE
VISUALS: Wizard needs OSO or Git credentials

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#781]
Met with Laura to review #767 from a visuals standpoint on her [InVision flow](https://redhat.invisionapp.com/share/23EVZUQRC):

- Overall visual treatment of the wizard needs work, since it's a new approach to wizards
- Modals need some work (might be able to re-use some stuff from
     - first pass at "Deleting Projects" flow we worked on before
     - Michael's work that included a screen for the "How would you like to get started" modal
- Dashboard card with tabs
     - find out if tabs are appropriate?
     - if so, how do we combine it into a dashboard card?

**Comment by catrobson** [comment]
@bdellasc is this obsolete can can close?

**Comment by bdellasc** [comment]
Yes. It appears obsolete. Closing it.
