### ISSUE TITLE
Experimental feature "got it" decision should persist per user

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#782]
When a user clicks "got it" on a experimental feature area on the green bar, that decision should be persisted across sessions per user.

Problem identified in this issue:  https://github.com/openshiftio/openshift.io/issues/1557#issuecomment-350278309

**Comment by catrobson** [comment]
Should persist across sessions even on user logout.

**Comment by dlabrecq** [comment]
Done. 

PR merged: fabric8-ui/fabric8-ui#2410
