### ISSUE TITLE
In-app Onboarding Experience?

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#783]
Should OSIO have an in-app onboarding experience? Something that first time users (or anyone who wants a refresher) are taken through to get them started.

There are a few key actions that always need to be done - could these be handled inside of the app vs only in documentation?

**Comment by catrobson** [comment]
There is an effort going on around Tour, which I will create an epic around.  Going to close this discussion to keep things clean.
