### ISSUE TITLE
Visual Design:  New App Wizard

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#790]
Visual designs for the [new app wizard page](https://github.com/fabric8-ui/fabric8-ux/issues/740) designed by Laura.

**Comment by bdellasc** [comment]
Still have a lot more work to do on individual screens, but wanted to get a first visuals pass on the general direction of the [progressive wizard](https://redhat.invisionapp.com/share/NPF3IQ67T). Will continue the work after shutdown.

**Comment by bdellasc** [comment]
Reviewed the current state of the visuals with @catrobson on Friday afternoon. Made all changes requested, but will need to work on the summary screen next sprint as it is more involved than originally done in the wire frames. Once summary screen is complete, will post to InVision.

**Comment by bdellasc** [comment]
Would like to get the team to review the design where it landed

**Comment by bdellasc** [comment]
I [updated the flows](https://redhat.invisionapp.com/share/VGF1RF15J#/272298383_Visuals_Cover_Page), but still feel like I need some more feedback from the team. Will keep it open briefly until I can can get feedback on it.

**Comment by bdellasc** [comment]
- Put some [thoughts](https://docs.google.com/document/d/1owdkpzrs468rLo9m1ZHazOyAjCZUxGTYLrZOMYBv7X8/edit?usp=sharing) and mocks together for #833 to discuss the visual design rationale with the OpenShift team
- In that meeting, we identified some gaps in the design that still need some work. We will create some stories to address them with @catrobson @Essjaysee 
- As a result of the meeting, updated the visuals and reorganized the flow, then posted to [InVision](https://redhat.invisionapp.com/share/VGF1RF15J)
- Got a bunch of other gaps filled in for the Launcher Experience including:
  - error states (naming Application, Application Setup)
  - previously authorized Git Provider
  - moved select & authorize Git Provider flow
