### ISSUE TITLE
Wireframe:  Error state for dashboard widgets with no permission/results

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#791]
There are dashboard widgets that won't be able to show information to the user such as Pipelines when they are looking at another person's space.  Come up with a design solution for these cases.  Look into this spreadsheet for permissions model:  https://docs.google.com/a/redhat.com/spreadsheets/d/1Tmsh3bfzShNLoOYZQAsFdNxXdkqeiV6bwIvgxg_cXBw/edit?usp=drive_web

**Comment by catrobson** [comment]
This should persist even on user log out.

**Comment by lwrigh** [comment]
@catrobson Here is a first pass of a few different options for handling widget errors. 

Invision link: https://redhat.invisionapp.com/share/38FCCR2WAM4
