### ISSUE TITLE
Design:  Delete deployment

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#796]
Document out how delete deployment would work and act on the deployments page, add to deployments InVision set.  This was discovered during a development review of the deployments page when they were not sure what the page should do, how the delete action acts for giving the user feedback, when they implemented it in the kabob menu.

**Comment by mceledonia** [comment]
[Design](https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273202263_Deployments_Delete) [INCOMPLETE]

**Comment by mceledonia** [comment]
Completed design, closing this one out.
