### ISSUE TITLE
Visuals/Dev-Animations and Transitions for New Wizard

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#798]
Verification Conditions:
- Create some animation concepts to show ideas
- Gather feedback on concepts
- Based on feedback, figure out what can be accomplished code-wise with @mindreeper2420

**Comment by mindreeper2420** [comment]
Connected to https://github.com/fabric8-ui/fabric8-ux/issues/803

**Comment by mindreeper2420** [comment]
@bdellasc @catrobson is this story still needed?

**Comment by bdellasc** [comment]
I do think this is a wider topic we should keep in mind for OSIO as a whole and something we try to address as we work on new designs throughout the UI. Transitions are always easier to vet when you can see them in action, as opposed to still mocks.

Since the launcher development is not being driven by us anymore, I'm not sure how much of the animations I spec'd will make it in (mostly around the overlay behavior). Ideally, if we could have done it and handed it off, it probably could have made it in. As far as the launcher, I don't know what options we have (if any) to make sure these are addressed. Might be something to talk about in retro...

**Comment by catrobson** [comment]
I'm going to close this, and add Animations as something to look at any 'standards' we want to set for OSIO as part of the design standards guide.
