### ISSUE TITLE
Dev: Help Joshua with AOT

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#805]
Multi-cluster issue: https://github.com/openshiftio/openshift.io/issues/1685

**Comment by dgutride** [comment]
Need to talk to Joshua a bit more about this - moving forward

**Comment by dgutride** [comment]
Moving back to backlog until @joshuawilson is ready to move forward

**Comment by catrobson** [comment]
@dgutride What is the status of this work?

**Comment by dgutride** [comment]
@catrobson  - it was moved to the backlog, nothing further was done about it but it was added to the list of architectural issues for the platform team to investigate.  We can remove it from here or close it at this point as it's unlikely we'll be doing this.

**Comment by catrobson** [comment]
Closing issue.  If something comes out for UXD, we'll capture as new issue in openshift.io backlog.
