### ISSUE TITLE
DEV: Change empty state of all cards to maintain + in header

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#809]
https://github.com/openshiftio/openshift.io/issues/1579#issuecomment-357137332

Maintain the circle + in the header of all cards even in empty state.  Need to capture all places where this exists and make sure we change them all in one PR.  Need to inform Todd of the change before the PR is approved so he can update his documentation.

**Comment by mindreeper2420** [comment]
Updated to keep the "+" icon in the Card Header, no matter whether the Card is in an empty state or showing Recent Spaces.

<img width="464" alt="screen shot 2018-01-12 at 10 26 26 am" src="https://user-images.githubusercontent.com/4032718/34882076-60238a6a-f783-11e7-997d-c46389efd261.png">
<img width="464" alt="screen shot 2018-01-12 at 10 28 07 am" src="https://user-images.githubusercontent.com/4032718/34882077-60318dcc-f783-11e7-8525-63d70a9ec021.png">

**Comment by catrobson** [comment]
PR submitted
