### ISSUE TITLE
VISUALS: Import Screens

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#812]

**Comment by bdellasc** [comment]
@lwrigh - please link to your InVision flow for my reference. Thanks!

**Comment by lwrigh** [comment]
Invision link: https://redhat.invisionapp.com/share/EGF2SMJQ3

**Comment by catrobson** [comment]
I believe this was already implemented, and we have the other story to review the implementation for visual design.  Can this story be closed @bdellasc?

**Comment by bdellasc** [comment]
Added [the import section](https://redhat.invisionapp.com/share/VGF1RF15J#/286895616_Launcher_Experience_Flow_-OSIO_-_Import-) to the larger Launcher InVision flow
