### ISSUE TITLE
VISUALS: Create Space

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#813]

**Comment by bdellasc** [comment]
@catrobson if you could please link in your wireframes to this story? Thanks

**Comment by catrobson** [comment]
This was the original wireframe idea, but please feel free to take creative freedoms on this as you see fit.

https://redhat.invisionapp.com/d/main#/console/11812379/249199293/preview

It was mean to have one page that replaces these two pages on OSIO today:
![image](https://user-images.githubusercontent.com/3739227/34948819-3d571276-f9dc-11e7-8827-e3249570f773.png)

![image](https://user-images.githubusercontent.com/3739227/34948855-52571a54-f9dc-11e7-81a1-717cbb702268.png)

**Comment by bdellasc** [comment]
Started a [concept for this design](https://redhat.invisionapp.com/share/98FFKV2U4JP#/274546255_Create_Space_-Default-_-_Visuals), based on the look/feel of the other similar pages, like "Experimental Features" landing screen and the "Create Application" screen. Need to get input and feedback on the visual direction
