### ISSUE TITLE
VISUAL:  Launch Experience visuals against PatternFly

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#833]
Perform a due diligence exercise to look at the visual design of what we're doing with the Launcher Experience as it compares visually to the Wizard from PatternFly (and especially the Wizard that the OpenShift team put into OpenShift).  Consider if we can pull the visual design "closer" to OpenShift and PatternFly, or if there are legitimate reasons why we need a different visual treatment.  Capture notes & visual work and share with Catherine, Serena, Colleen.

**Comment by bdellasc** [comment]
Worked with the team to put together some design rationale notes. Will review with @catrobson and @Essjaysee and put something together for the OSO<->OSIO synch up meeting.

**Comment by bdellasc** [comment]
Reviewed the design rationale notes with @Essjaysee and @catrobson, pulled mocks together for the synch.
