### ISSUE TITLE
DEV: Pipelines page kabob cleanup

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#834]
On the pipelines page, we want to remove the following items from the kebab menu
![image](https://user-images.githubusercontent.com/3739227/35195650-c210fc90-fe94-11e7-8b8d-6aa956f3a9b3.png)

- Stage: blah
- Run: blah
- View last build 
- View Test Report
- Edit Pipeline (Edit Pipeline on the page that brings you to OpenShift Build Config can stay, just remove from kabob)

We should also be removing the "View last build" page in OpenShift.io, as all this information can be easily found in the OpenShift Console.

Related OpenShift.io issues that should be tagged/resolved as this is fixed:
https://github.com/openshiftio/openshift.io/issues/1945
https://github.com/openshiftio/openshift.io/issues/1678
https://github.com/openshiftio/openshift.io/issues/981

FYI @joshuawilson

**Comment by joshuawilson** [comment]
cc @sthaha @chmouel @pradeepto
