### ISSUE TITLE
HTML/CSS: Cleanup on Feature Flags

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#837]
Review the Feature Flags updates that have been done to fabric8-ui. Update HTML/CSS to match designs.

**Comment by mindreeper2420** [comment]
Issues to resolve:

- [ ] https://github.com/openshiftio/openshift.io/issues/1955
- [ ] https://github.com/openshiftio/openshift.io/issues/1956

**Comment by mindreeper2420** [comment]
Updated the `.btn-feature-level` styles to use proper gradients and implemented the `:hover` styles. Fixed a spelling error in the `.btn-experimental` class for the banner that caused the styles to not be applied.

**Comment by corinnekrych** [comment]
fixed with https://github.com/fabric8-ui/fabric8-ui/pull/2428 @mindreeper2420 pls close it
