### ISSUE TITLE
Wireframe: Import codebase flow

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#839]
The current import codebase flow is confusing and misleading for users.  We need to clean up the distinction between importing a codebase that just shows a github or other git linked codebase vs. creating an application that links a codebase to the pipelines and full OSIO process.

Valdiation criteria:
- [ ] Capture current flows
- [ ] Capture desired flows
- [ ] Capture any screen design updates as wireframes
- [ ] Post to Fabric8 wiki, src files to google drive
- [ ] Share with UX/UI team for review
- [ ] Share wtih devtools-saas for review
- [ ] Create necessary followup stories for implementation

**Comment by catrobson** [comment]
Related OpenShift.io issue:  https://github.com/fabric8-ui/fabric8-ux/issues/839

**Comment by catrobson** [comment]
@lwrigh please also consider the following issue: https://github.com/openshiftio/openshift.io/issues/282#issuecomment-361428265

We need to make sure that the github repo they are choosing is a public one.

**Comment by aslakknutsen** [comment]
@catrobson @lwrigh @qodfathr I would suspect the 'only public repo' import to be a good place for a 'need private access? upgrade to pro' hint. Whenever we get there...

**Comment by lwrigh** [comment]
@catrobson Here's the current flow captured: https://redhat.invisionapp.com/share/DTFOUUVAMZ4

**Comment by catrobson** [comment]
@qodfathr - want to verify whether you want to continue to support codebases that do not have any attachment to a pipeline in OSIO.  These are then just links to GitHub, and users can create Che Workspaces on them, but they cannot automatically deploy through OSIO to OSO.  Attaching a pipeline "after the fact" would then have to be a separate action where the user goes through the launcher experience to import the codebase _again_ in that flow.

**Comment by lwrigh** [comment]
@catrobson I updated the current flow and added a flow diagram based off of the comments you left yesterday. I also included a flow diagram with a proposal for a new codebase flow. https://redhat.invisionapp.com/share/DTFOUUVAMZ4

**Comment by lwrigh** [comment]
@catrobson I added a first pass at wireframes of importing a codebase from the application wizard. I added it to the same Invision document from the previous comment.

**Comment by qodfathr** [comment]
@catrobson as we discussed, I'm okay with codebases that do not have a pipeline. I also understand that running the appwizard to import the codebase is really the only way to get a pipeline attached.

Will this lead to the codebase being listed twice? If yes, that may become a high-priority issue to address,

We definitely want to revisit this experience. It should be possible to add or even change the pipeline associated with a codebase. That design should be considered hand-in-hand with how we'll be dealing with branches and HDD. One could imagine each branch of a codebase having a different pipeline (or some having none at all). And maybe some branches have more than one pipeline? Lots of use cases to be considered.

**Comment by aslakknutsen** [comment]
The duplicate codebase bit is a bug; https://github.com/fabric8-services/fabric8-wit/issues/1294

**Comment by lwrigh** [comment]
@catrobson Here's the latest version of the import codebases flow and wireframes: https://redhat.invisionapp.com/share/APFU0FUYS2U

**Comment by lwrigh** [comment]
@catrobson Here's the latest version of the import codebases/import existing projects flow: https://redhat.invisionapp.com/share/APFU0FUYS2U

Based off of the codebases meeting this morning it seems like the merged flow, not the quick add, seems like the direction this flow will end up taking.

**Comment by catrobson** [comment]
Thanks @lwrigh for the updates.  I think we're good to close this issue and create a visual design issue for the story.  Can you create that?

**Comment by lwrigh** [comment]
Yup I can create a visual design story for it.
