### ISSUE TITLE
DEV: public/private e-mail address 

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#841]
HTML/CSS for adding a public/private option to the user's e-mail address in their user profile.
Need to also handle the e-mail address not being shown on a user's profile if they select private.

Wireframes:
https://redhat.invisionapp.com/share/72F2YPYUY#/screens/269843926

**Comment by mindreeper2420** [comment]
Code merged with working services in new PR: https://github.com/fabric8-ui/fabric8-ui/pull/2489
