### ISSUE TITLE
Dev: Launcher Experience component work

### ISSUE THREAD

**Issue by dgutride** [fabric8-ui/fabric8-ux#846]
Still need to do:

1) Wire up OK button on each screen
2) Add validation PUT call to final step through abstract service
3) Add dummy timeout response for final POST to simulate websocket behaviour
4) Add zip file download screen (toggle between zip download and create screen depending on user selection)
5) Figure out way to modify which steps show via configuration (only target environment should be hidden on OpenShift.io)

**Comment by dlabrecq** [comment]
The above items have been implemented, but keeping this open until the team has a chance to review the launcher.
