### ISSUE TITLE
DEV: Remove all empty state icons

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#849]
For the empty states across the product, we currently use an icon.  These have caused confusion for users who think these are actionable.  Remove these icons.

Let's see if we can capture a list of all locations below as well so we're tracking this & it can be tested on PR.

- [x] User Homepage/Dashboard
- [x] Space Dashboard
- [x] Planner list 
- [x] Codebases list
- [ ] Pipelines list (currently looks like it needs a empty state?)
- [ ] Deployments?  (Need to talk with Michael Celedonia about what is desirable)

**Comment by mindreeper2420** [comment]
@catrobson Currently, there are no empty states for Pipelines, Applications, Environments and Deployments. Do you want to leave them as is, or spin up a separate story to have empty states created for those pages?

**Comment by catrobson** [comment]
@mindreeper2420 Applications, Environments are going away, so no need to change them.  Pipelines should probably have an empty state, so I'll create a story to look at that.

**Comment by mindreeper2420** [comment]
@catrobson ok, sounds good. I'll close this then, as the two PRs have been merged.
