### ISSUE TITLE
Design: Full page error/statement pages

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#859]
Standardize the design for full page error pages or statement pages to the user.  Work with Sukhvir on implementation of HTML/CSS of this.  Should have common layout and determine if we need illustrations for anything.

Examples:
* 404 page (and its variants)
* Email validation page
* OSO projects need to be removed page

**Comment by mceledonia** [comment]
[Designs here](https://redhat.invisionapp.com/share/64FX5EFGWXT)
