### ISSUE TITLE
DESIGN: Launch Experience UI Copy - Runtimes & Mission

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#860]
VCs:
Gather content for the various options from places for the things.

- What is a mission?
- Description for each mission
- Description for each runtime (see https://developers.redhat.com/launch/filtered-wizard/all)
- When an item is disabled because it is not a match, add copy about why it is disabled
- Copy for suggested mission and suggested runtime

[Screen in InVision](https://redhat.invisionapp.com/share/VGF1RF15J#/275859938_Select_R_And_M_1_-_Visuals)

**Comment by stacymcauliffe** [comment]
Provided first pass for usability testing and will need to revise based on feedback. 
-Introduce boosters
-Make it more clear what a mission is and what choosing a mission/runtime combination accomplishes
-Revise and shorten mission and runtime descriptions

**Comment by stacymcauliffe** [comment]
Created issue for dev: https://github.com/openshiftio/openshift.io/issues/2673

Closing this and will track changes there.
