### ISSUE TITLE
DESIGN: Launch Experience UI Copy - Additional Content

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#863]
VCs:
Work with SMEs on polishing content for:
- Use real labels on stages in pipelines
- Describe why we suggest a pipeline
- Describe why we want you to connect w/ GitHub, what we will write there, what we will read from it
- Does the Summary screen need an explanation of what it's about to go off and build?
- Next steps pages (Next Steps: Set Up New Application, Next Steps: Activate Booster) 

[Screens in InVision](https://redhat.invisionapp.com/share/VGF1RF15J#/275860322_Select_A_Release_Strategy_-Default-_-_Visuals)

**Comment by stacymcauliffe** [comment]
After usability test, need to revisit the pipeline work - why are we suggesting a pipeline, edit descriptions of each pipeline

**Comment by stacymcauliffe** [comment]
Created issue for dev: https://github.com/openshiftio/openshift.io/issues/2673

Closing this and will track changes there.
