### ISSUE TITLE
FLOW:  OSO Connect Automatically

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#864]
Capture the flow and edge cases for OSO connecting automatically so we can capture any variants and understand the full flow given authentication states.

**Comment by dgutride** [comment]
New flow documented here:  https://docs.google.com/document/d/1OQEpEmDoGi6TI58xyobbAat0L8i3A3Z67CCLS-AjZC0/edit?usp=sharing - need feedback @qodfathr @alexeykazakov @sbose78

**Comment by qodfathr** [comment]
Looks good to me. I added a comment.

**Comment by dgutride** [comment]
@qodfathr @catrobson - one open question on what we should do if linking fails (instead of putting the user in a redirect loop)

**Comment by dgutride** [comment]
Design created to handle failed linking - this can be closed.
