### ISSUE TITLE
VISUALS:  Loader for Che

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#868]
We have some change in the way we are going to load the IDE.
Until now, the when user's workspace was started, we were displaying the IDE and in the IDE showing the loading of all the workspace's containers. Once all workspace's containers were ready, we let the user being able to interact with the file

With the new IDE that we are introducing, that will be a little bit different:
1. The IDE is not be available upfront
2. We have an intermediate step while the IDE is getting assembled (depending on plugins selection)
3. We then start the IDE
4. Once the IDE is ready, we display it and make it "available" for editing
5. Workspace's containers are loaded in parallel (but that does not prevent the user to start interacting with its file for example) 

I would think that this gives us an opportunity to make a really creative loader.  know that this would be something low regarding your other priorities, but do you think it is something your team could help us to build?

@ashumilova and @slemeur can brainstorm with you on ideas for what we might want to do.

- [Meeting notes from 27 Feb 2018](https://docs.google.com/document/d/16-4m2nZMaxEAOrquVCAE6FmR_gZpLKtCJ4LqA-NgQpY/edit?usp=sharing)
- Link to [loader video](https://youtu.be/ra8MlcddbBs) of IDE loading
- [Reference/inspiration images](https://drive.google.com/open?id=19m7jl7X6Pf2t9ixwLlrWShQt1DKKfTBj)
- [Links to other inspiration imagery](https://docs.google.com/document/d/1K9FcIOHxL0G4lUdgeTSrm5zPSrwN8NS8TiV98Isxo3w/edit?usp=sharing)

**Comment by bdellasc** [comment]
Located and reviewed the content and references from late February's meeting. Starting concept ideas now.

**Comment by bdellasc** [comment]
Moved to the openshift.io repository [#2875](https://github.com/openshiftio/openshift.io/issues/2875)
