### ISSUE TITLE
HTML/CSS:  Card with list view custom style set

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#872]
Come up with a custom set of styles to apply to cards with list views for OSIO and Launcher.  Work with Brian to solidify what this should be so it works across our current designs well.

**Comment by mindreeper2420** [comment]
Codepen examples can be found here:

- [Base Card w/List](https://codepen.io/mindreeper2420/pen/wymQON)
- [Card w/Full Description](https://codepen.io/mindreeper2420/pen/vdrzjj)
- [Card w/Images](https://codepen.io/mindreeper2420/pen/xYzmKZ)

**Comment by mindreeper2420** [comment]
Added as a component to the Launcher (ngx-launcher) and implemented in the Mission/Runtime section.

Working on converting the existing cards in additional sections.

**Comment by mindreeper2420** [comment]
At this time, these will not be implemented. We will continue down the path of overwriting the current PatternFly cards, creating custom styles inside of fabric8-ui. At a future date, we will gather all of the custom elements from OpenShift.io and create a list of patterns to contribute to PatternFly.
