### ISSUE TITLE
HTML/CSS:  Navigation prototype for left-hand Nav

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#884]
Create left-hand nav as a HTML/CSS prototype with screenshots of real screens behind them to give context.

The design prototype to build from:
https://redhat.invisionapp.com/share/N5F0DF7PY#/screens/270120614

Design contacts:
@catrobson, @mceledonia

**Comment by catrobson** [comment]
@SMahil can you post link to where this is hosted?

**Comment by SMahil** [comment]
https://rawgit.com/SMahil/leftnav/master/index.html
