### ISSUE TITLE
DESIGN: Sensible profile picture interaction and upload

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#886]
Gravatar is currently used for importing a profile picture and the interaction is a bit odd right now. Do some research and come up with different solutions for the interaction between importing or uploading a profile picture to Openshift.io.

**Comment by lwrigh** [comment]
@catrobson Here's a first pass at trying to make the upload a new profile picture interaction less awkward: https://redhat.invisionapp.com/share/2FFY8Z58CGQ

**Comment by catrobson** [comment]
@lwrigh can you initiate a discussion with Auth team and Platform team about the profile picture and whether we can actually store a picture in our system or not?  Right now we use internet based profile pictures because we cannot, so I don't know if we can change that requirement.  Maybe e-mail or mattermost to start?

**Comment by lwrigh** [comment]
@catrobson Thank you for bringing that up, I can reach out to both teams and ask.

**Comment by lwrigh** [comment]
@catrobson Here's the latest version of the wireframes that feature notes: https://redhat.invisionapp.com/share/SXG1RKFTH87

**Comment by stacymcauliffe** [comment]
@lwrigh copy review & suggestions here: https://docs.google.com/presentation/d/1Js8KNEHiX-pDp6uMwOg4OzjJC-l2vTO1CdpNr93rqlQ/edit?usp=sharing

**Comment by lwrigh** [comment]
@stacymcauliffe Great thank you so much for the suggestions! I can update the wireframes accordingly.

**Comment by lwrigh** [comment]
The copy has been updated to match Stacy's suggestions.
