### ISSUE TITLE
DESIGN & COPY: Create Space Overlay

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#888]
See #911 HTML/CSS: Update Create Space and Import Overlays per Visual Design for latest HTML/CSS.

VCs:
- [x] Add additional copy to explain Spaces 
- [x] New/updated copy to explain what scenario-driven design and the other development methodologies are?  
- [x] Where does the copy about the development methodologies live?
- [x] Take out "new" from the page title
- [x] Update copy for "I plan things" and "I do things"

Conversations resulted in 2 possible options:

**Option A (3 options along bottom of screen)**
- [x] Add third option to design for "Empty Space"
- [x] Create copy as needed for "Empty Space" -- the third option
- [x] Should all 3 options be equivalent, weighted equally?
- [x] Relabel the 3 options, maybe?
- [x] Work with @mindreeper2420 & @dlabrecq to get it implemented - see issue #

**Option B (just return the user to the new space dashboard)**

**Comment by Veethika** [comment]
@muruGanesan

**Comment by stacymcauliffe** [comment]
Copy document is here: https://docs.google.com/document/d/1-MbsbeO6VmrzTYs12riUMnMlOzFgma_wyXBAV_RmVmU/edit?usp=sharing

**Comment by bdellasc** [comment]
We had a conversation about the options along the bottom of the overlay, but it seemed like we were leaning more in the direction of just taking the user back to the new space's dashboard. This would give the user a more consistent experience when they want to crate a new application. The could also link off to the planner or anything else they want to set up for the new space.
Posted V2 to [InVision](https://redhat.invisionapp.com/share/U5FISV94GMD)

**Comment by bdellasc** [comment]
Fielded a few questions from @lwrigh . Think this story is done.
