### ISSUE TITLE
DESIGN & COPY: Create Application Overlay

### ISSUE THREAD

**Issue by bdellasc** [fabric8-ui/fabric8-ux#889]
VCs:
- Add "Name" field to UI
- Add copy for Application description, new & import options
- Work with @mindreeper2420 & @dlabrecq to get it implemented
- Follow-up to #896

**Comment by bdellasc** [comment]
Completed another pass at this screen. Worked with @stacymcauliffe on the content. She would need to verify the general error message at the top of the screen when there is a problem with what the user entered (the final screen in the flow).

[InVision mockups here](https://redhat.invisionapp.com/share/54G64RKRSXK)

**Comment by bdellasc** [comment]
Completed the text content [updates to the flow](https://redhat.invisionapp.com/share/54G64RKRSXK) for the OSIO case. Will update the create application overlay for the Launch case in the larger, main InVision document. I believe #896 can be closed since we've got a new story for this overlay here.

**Comment by stacymcauliffe** [comment]
Created issue for dev: https://github.com/openshiftio/openshift.io/issues/2673

Closing this and will track changes there.
