### ISSUE TITLE
Permissions and Authentication Conversations

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#892]
Informal conversations with SMEs around Red Hat about authentication and permissions.  Topics can emerge from research of other systems, but some areas to cover:

* Common terminology that is expected.  https://docs.google.com/document/d/1TQsoRI6xUN-6ih7wKgovPlYnvOGtd38rWvmWz-wYnSA/edit#heading=h.x04ui2crotnq. Do they know what "security groups" are?  How do they talk about permissions, roles, security groups?

* Inheritance and how to deal with the complexity of grouping and inheritance in permissions.  How much flexibility vs. usability do they want when working with these systems.  Where is the line, and what are they willing to do when they need full flexibility vs. when they just want to do basic setup?

**Comment by lwrigh** [comment]
@catrobson Here's the current working list of questions to ask participants: https://docs.google.com/document/d/1yyoFyGTIx-6RlncDhYFG_QgU4TmIYcba6mJs4J00l7Y/edit?usp=sharing

**Comment by lwrigh** [comment]
@catrobson Here's a brief summary of some of the insights gathered from the user interviews https://docs.google.com/document/d/1LQo6d40e6jRDu3BHW6LYbKueQ6WcisfMKCbhrmdQ4Pg/edit?usp=sharing

**Comment by lwrigh** [comment]
Going to send out another email to boston-list to try to recruit a few more participants.
