### ISSUE TITLE
HTML/CSS: 404 page updates

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#894]
Update 404 pages to reflect new visual design which standardizes the layout and pattern used for these types of full page layouts.

https://redhat.invisionapp.com/share/64FX5EFGWXT

**Comment by mindreeper2420** [comment]
![screen shot 2018-03-12 at 2 38 27 pm](https://user-images.githubusercontent.com/4032718/37303165-01d031fc-2604-11e8-8e74-b5e5bdd63582.png)

**Comment by mindreeper2420** [comment]
PR was submitted using the image above, but it was closed due to a request to change the image. Once that image is updated, a new PR will be submitted.

**Comment by mindreeper2420** [comment]
PR filed https://github.com/fabric8-ui/fabric8-ui/pull/2654

**New Image**
<img width="721" alt="screen shot 2018-03-21 at 2 38 44 pm" src="https://user-images.githubusercontent.com/4032718/37731863-ca007972-2d19-11e8-99f2-c9df640ec33e.png">

**Comment by mindreeper2420** [comment]
PR merged.
