### ISSUE TITLE
VISUAL DESIGN: Launcher experience mockup updates (for usability study #2)

### ISSUE THREAD

**Issue by Essjaysee** [fabric8-ui/fabric8-ux#895]
After convo w/ @essjaysee and @mindreeper2420, @bdellasc to make updates to mocks for the next usability testing iteration:

- Move pipeline visualization as primary item within the row, move the detail copy to be in the expansion
- Find new illustrations to replace import and create icons
- On M&R page, how to show copy that describes why an item was disabled
- On GitHub screen, make image smaller to make room for copy describing what we will do with your information
- On M&R page, add warning on the secured mission
- On M&R page, add tech preview label on node.js

- On M&R page, add proficiency level with link (backburner for now)

**Comment by bdellasc** [comment]
Met with @dlabrecq and @Essjaysee RE: status of the Launcher usability demo. Here's what we decided:

**- Unhook API feeds for demo content**
**- Use [new copy](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing
)provided by @stacymcauliffe to populate the UI**
**- Only focus on these two main flows:**
   - From Red Hat Developers Launch -> Create Application via an Openshift Online Environment
   - From OSIO -> Happy Path that is completely visible from the getgo
**- Behavior of the launcher:**
   - Continue Buttons remain, remove cancel button
   - Floating Cancel X in the upper right
   - Summary always visible
   - Bar behind the section circles in the left panel is solid all the way through, now that the summary is always visible. Doesn't fade back when flow is not totally visible.
**- Start Overlay:**
   - Use the layout with the import/create options
   - Add toggle so we can switch between the two main flows (see first bullet)
**- Selection behavior on cards and list rows is the same:**
   - Click anywhere to activate the radio button (including the radio button itself)
   - Expansion only when clicking on the expansion arrow
**- Mission and Runtime description text**
   - 100ish characters as the preview, appended with "more" link
   - "more" link reveals the rest of the description in the row
- When canceling out of the launcher, it brings the user back to space dashboard
-

**Comment by bdellasc** [comment]
Notes from Launcher Synch - 27 Feb
Attendees @catrobson , @dlabrecq , @mindreeper2420 , @bdellasc, @stacymcauliffe 

Reviewed current state of launcher. Feedback:
==================
==================
**Both Flows (#3)**
- Default Name in the overlay
==================
**Select Mission & Runtime (#1)**
- truncation on Mission/Runtime - Adam and Dan to synch up on how to implement it
**"Suggested"**
- Only applies to Missions, remove from Runtimes
- Criteria for "Suggested" will change depending on the situations, will need to be fed from the back end. For demo, placeholder text from Stacy.
**"InCompatible" vs "Contribute"**
- "Incompatible" becomes "Contribute" for Runtimes
- "Contribute?" becomes "Contribute" for Missions
- "Contribute" for both Runtimes and Missions link to the same page
==================
**Target Environment (after demo)**
- Remove middle row of content describing Openshift Online vs .ZIP Download
- Add Label to .ZIP icon "ZIP File"
==================
**Select Pipeline (nice to have)**
- Minor spacing feedback (can wait until after demo)
- Remove "Technology Preview" tag from Row
==================
**Authorize Git Provider (nice to have)**
- Move the "what we do with your GitHub stuff" content into the left side of the card
==================
==================
OpenShift.io Flow
**Summary (#2)** 
- Fix pipelines visualization to match the Pipelines section (without radio button)
- Hide the "Target Environment" from Application Info card

**Comment by bdellasc** [comment]
Got this stuff folded in for the testing.
