### ISSUE TITLE
VISUALS:  Create application screen for Red Hat Developer Launch vs. OSIO

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#896]
We have a visual design for the Red Hat Developer Launch initial screen where the user names their application here:  https://redhat.invisionapp.com/d/#/console/12879000/275859322/preview

The team discussed another variant of this screen that we would use for OSIO to decrease the amount of screens the user needs to click through that combines the application naming with the choice for importing or creating a new application.  A visual design is needed for this variant.

**Comment by catrobson** [comment]
@mindreeper2420 can you add a screen shot of what you have implemented already for the OSIO variant of this screen?

**Comment by mindreeper2420** [comment]
**OSIO**
<img width="1364" alt="screen shot 2018-02-26 at 9 47 01 am" src="https://user-images.githubusercontent.com/4032718/36676589-0faf5c88-1ada-11e8-8105-dd96ed108d18.png">

**Launch**
<img width="832" alt="screen shot 2018-02-26 at 9 47 09 am" src="https://user-images.githubusercontent.com/4032718/36676623-26a45e48-1ada-11e8-999b-7aa190d504e1.png">

**Comment by bdellasc** [comment]
First pass at the screen [here](https://redhat.invisionapp.com/share/6RG2UP82TQ8)

**Comment by bdellasc** [comment]
Second pass at the screen posted in comments [here](https://github.com/fabric8-ui/fabric8-ux/issues/889)

**Comment by bdellasc** [comment]
Completed the text content [updates to the flow](https://redhat.invisionapp.com/share/54G64RKRSXK) for the OSIO case. Will update the create application overlay for the Launch case in the larger, main InVision document.
