### ISSUE TITLE
Flow:  OpenShift.io registration queueing

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#897]
Capture the expected user flow, pages changes, and system changes we want users to have given the new description of how Todd wants the user registration process to run.  Ideally capture what would be owned by Platform/UXD (UI changes), Auth (OSIO authentication changes), OpenShift Online (registration UI updates), and Marketing (e-mail changes) in this flow with a key so that we can clearly track each team's contributions towards the larger flow and experience being asked for.

**Comment by catrobson** [comment]
Todd's experience:  https://github.com/openshiftio/openshift.io/issues/2109

**Comment by lwrigh** [comment]
@catrobson Here's a first pass at documenting the registration depending on capacity workflow: https://redhat.invisionapp.com/share/ZYG1W2GT5FM

**Comment by lwrigh** [comment]
Talk to Dana, Adam, and Alexey about it. Schedule that for this current week.
