### ISSUE TITLE
HTML/CSS: Navigation prototype #2 - Mega Menu Desktop with Bottom mobile nav

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#899]
Create a HTML/CSS prototype in a local environment that can be posted to a rawgit for demoing to the team following the designs found here:
https://redhat.invisionapp.com/share/29EZHR8N3#/screens/269560197

**Comment by mindreeper2420** [comment]
GitHub repository for prototype: https://github.com/mindreeper2420/megamenu

Rawgit URL for prototype: https://rawgit.com/mindreeper2420/megamenu/master/index.html

**Comment by mindreeper2420** [comment]
Initial prototypes created. I made two separate, specific ones due to time.

**Comment by mindreeper2420** [comment]
To view the mobile navigation, shrink the browser down to 900px in width (or below). If visited on a mobile device, the user will automatically be shown the mobile view.

**Comment by mindreeper2420** [comment]
**Desktop View:**
<img width="1920" alt="screen shot 2018-03-02 at 12 44 34 pm" src="https://user-images.githubusercontent.com/4032718/36913329-9267a442-1e17-11e8-9e2e-c020d17ff2a5.png">

**Mobile View:**
<img width="606" alt="screen shot 2018-03-02 at 12 44 44 pm" src="https://user-images.githubusercontent.com/4032718/36913335-9951b3c4-1e17-11e8-855f-b1c690ac338c.png">

**Comment by mindreeper2420** [comment]
Improved animations of the menus by making the megamenu appear faster and the mobile menu now moves from bottom to top, with a smooth transition.

The anchor for the megamen (what starts off as 'Space') updates to show the current space that the user is in when they open up that subsection of the menu.

**Comment by mindreeper2420** [comment]
**Megamenu Expanded:**
<img width="1920" alt="screen shot 2018-03-02 at 5 21 28 pm" src="https://user-images.githubusercontent.com/4032718/36924845-41d615e6-1e3e-11e8-83ce-d192a8cb8882.png">
<img width="1920" alt="screen shot 2018-03-02 at 5 21 35 pm" src="https://user-images.githubusercontent.com/4032718/36924846-41e5791e-1e3e-11e8-9a29-5e13de3380ce.png">

**Mobile Menu Expanded:**
<img width="542" alt="screen shot 2018-03-02 at 5 21 45 pm" src="https://user-images.githubusercontent.com/4032718/36924856-4ab70724-1e3e-11e8-9d72-3a1cc7147832.png">

**Comment by mindreeper2420** [comment]
@catrobson I've updated the prototype with a new animation for the mobile menu and changed the animation speeds for the mega menu.
