### ISSUE TITLE
VISUAL DESIGN: Upload profile picture

### ISSUE THREAD

**Issue by lwrigh** [fabric8-ui/fabric8-ux#915]
Invision link: https://redhat.invisionapp.com/share/2AG4W0HY8EH
Wireframes story: https://github.com/fabric8-ui/fabric8-ux/issues/886

First pass at visual design for the upload profile picture flow.

**Comment by mceledonia** [comment]
Invision Link (pending)

@lwrigh Can you close this issue when you get the chance? :)

**Comment by lwrigh** [comment]
@mceledonia Yup can close this one too
