### ISSUE TITLE
Wireframes: Designs for email verification status

### ISSUE THREAD

**Issue by rohitkrai03** [fabric8-ui/fabric8-ux#920]
Related to https://github.com/fabric8-services/fabric8-auth/issues/262

What is expected on profile overview page:

- Show if email is verified or not on user profile page
- Add "verify" action for unverified emails

**Comment by catrobson** [comment]
https://redhat.invisionapp.com/share/E9FH915D3U7

As commented on https://github.com/fabric8-services/fabric8-auth/issues/262 I don't agree that these actions should be raised to the user in the UI.  It doesn't feel like we need a status or action on the user profile.  If the user tries to navigate into OSIO with an unverified e-mail shouldn't we just redirect them to a verify your e-mail page?

**Comment by alexeykazakov** [comment]
@catrobson any comments to https://github.com/fabric8-services/fabric8-auth/issues/262#issuecomment-372743630 ?

**Comment by rohitkrai03** [comment]
Closing.
