### ISSUE TITLE
Verify Consistency of Modals vs Overlays

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#935]
Verify the usage of modals vs overlays in OpenShift.io. Make sure that both are used properly and, if not, fixed the use cases to match design schematics.

**Comment by mindreeper2420** [comment]
## Current Modals:
**Create Space - Connect to GitHub**
<img width="1920" alt="screen shot 2018-03-21 at 1 41 04 pm" src="https://user-images.githubusercontent.com/4032718/37728169-f5461c36-2d0f-11e8-8869-1b6869245538.png">

**Create Space - Add New Space**
<img width="1920" alt="screen shot 2018-03-21 at 1 58 58 pm" src="https://user-images.githubusercontent.com/4032718/37728191-054fe5e4-2d10-11e8-9212-647cd438158a.png">

**Add to Space**
<img width="1920" alt="screen shot 2018-03-21 at 1 42 47 pm" src="https://user-images.githubusercontent.com/4032718/37728205-0fb5641e-2d10-11e8-8f13-83e864310370.png">

**Add New Area/Child Area**
<img width="1920" alt="screen shot 2018-03-21 at 1 43 10 pm" src="https://user-images.githubusercontent.com/4032718/37728243-1e0db304-2d10-11e8-8234-dd98f1bdd314.png">

**Add Collaborators**
<img width="1920" alt="screen shot 2018-03-21 at 1 43 26 pm" src="https://user-images.githubusercontent.com/4032718/37728250-2513ecc2-2d10-11e8-8f78-4c3c98d51917.png">

**About Modal**
<img width="872" alt="screen shot 2018-03-21 at 2 00 44 pm" src="https://user-images.githubusercontent.com/4032718/37728299-45030efa-2d10-11e8-9c2a-89e71b07d2e2.png">

## Current Panel
**Add Codebase**
<img width="1920" alt="screen shot 2018-03-21 at 1 42 18 pm" src="https://user-images.githubusercontent.com/4032718/37728283-372e9880-2d10-11e8-89bd-a902e8d33bbb.png">

**Comment by catrobson** [comment]
Closing, created duplicated issue into openshift.io/openshift.io github:  https://github.com/openshiftio/openshift.io/issues/2846
