### ISSUE TITLE
Dev: Space Dashboard

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#937]
As part of the new Space Dashboard work, a new cards were designed. The dashboard has already been created in HTML/CSS (issue #925 and PR https://github.com/fabric8-ui/fabric8-ui/pull/2662), but is not yet hooked up. This will need to be done before it can be pushed to production and flags removed.

Verification:
- [ ] Active Applications card connected and matches [designs](https://redhat.invisionapp.com/d/main#/console/13117756/283827734/preview)
- [ ] Internal Feature Flag and Development Flags removed from all components used by the Space Dashboard

**Comment by catrobson** [comment]
@mindreeper2420 is still something that needs to be done?

**Comment by mindreeper2420** [comment]
@catrobson yes - the JS is not hooked up and the new Workspaces card is just a placeholder. Functionality is still missing in regards to connecting to the backend and Workspaces APIs.

**Comment by AdamJ** [comment]
outdated - closing
