### ISSUE TITLE
Update Planner to use CSS animations rather than Angular animations

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#938]
There is currently a issue with OSIO that is caused by aspects of Angular 4 (see https://github.com/openshiftio/openshift.io/issues/2339) and an animations module.

As part of this, there is a request to remove the Angular animations module that has been attributed to these issues, and replace them with CSS animations.

**Comment by AdamJ** [comment]
outdated - closing
